
//==========================================================================
//
// Character Animation Script     Z O M B I E S
//
// All player states should have animations sutable for a two handed rifle type weapon.
//
// This defines the animations and events that might occur at different times
// for this character. State changes, and random behaviour during idle/alert
// states will look here for default behaviour, if that character doesn't have
// something specific in their scripts for that level.
//
//==========================================================================

// playerAnimType:
// Set in "Player Anim Type" in the weapon gdt file.
// Full list specified in playeranimtypes.txt.
// Asset manager choices specified in weapon gdf files.

//==========================================================================
// DEFINES
//
// These can be used to simplify the scripting, by defining replacement strings

DEFINES
// moveStatus
set movestatus moving = walk AND run

// weaponclasses
set weaponclass autofire = mg AND smg

// playerAnimTypes
set playerAnimType grenadeonly = all NOT m203 NOT briefcase

#ADD_VEHICLE sitting_jeep tank drivers 1 gunners 1
#ADD_VEHICLE huey default drivers 1 gunners 2 passengers 6
#ADD_VEHICLE pbr default drivers 1 gunners 4 passengers 0

//==========================================================================
// ANIMATIONS
//
//	NOTE: scripts are chosen by first-come-first-serve basis. The first match
//	found is the one used.
//
// format:
//
// state <state description>
// {
//		<movement type>
//		{
//			[DEFAULT / <condition type> [<condition value>], ...]
//			{
//				<both/legs/torso/turret> <animation> [sound <filename>]
//				<both/legs/torso/turret> <animation> [sound <filename>]
//				...
//			}
//		}
//	}
//
//	legend:
//
//	<state description>: relaxed, alert, combat
//
//	<movement type>: idle, idlecr, idleprone,
//                   walk, walkbk, walkcr, walkcrbk, walkprone, walkpronebk.
//                   run, runbk, runcr, runcrbk,
//                   straferight, strafeleft, turnright, turnleft
//
//	<condition type>: playerAnimType, weaponclass, position, enemy_weapon, underwater, mounted, movestatus, underhand, leaning, weapon_position, perk, cac, riotshieldnext
//
//	<condition value>:
//
//		playerAnimType: <weapon Player Anim Type in gdt>
//		position: behind, infront, right, left
//		enemy_weapon: <see weapon pickup names>
//		underwater: <no values>
//		mounted: mg42
//		movestatus: <see movement types>
//		underhand: <no values>
//		leaning: right, left
//		weaponclass: rifle, sniper, smg, mg, pistol, grenade, rocketlauncher, flamethrower, turret, non-player
//		weapon_position: hip, ads
//		direction: not, left, right - will never be left or right while moving backward
//		perk: laststand, grenadedeath
//		attachment: bayonet
//		riotshieldnext: <no values>
//		cac: <no values>
//
// NOTES:
// - The player walks when they are ADS, so they can not ADS while running.
//

ANIMATIONS

STATE COMBAT
{
	idle
	{
		// LASTSTAND
		perk laststand, stance prone
		{
			both pb_laststand_idle
		}
		perk laststand, stance crouch
		{
			both pb_laststand_idle
		}
		perk laststand
		{
			both pb_laststand_idle
		}
		// TURNED
		playerAnimType turned, stance prone
		{
			both pb_zombie_crawl_idle
		}
		playerAnimType turned, stance crouch
		{
			both pb_zombie_crawl_idle
		}
		playerAnimType turned
		{
			both pb_zombie_idle
		}
		// REMOTE CONTROL
//		playerAnimType remotecontrol, stance prone
//		{
//			both pb_rc_prone_idle
//		}
//		playerAnimType remotecontrol, stance crouch
//		{
//			both pb_rc_crouch_idle
//		}
//		playerAnimType remotecontrol
//		{
//			both pb_rc_stand_idle
//		}
		// SCREECHER
		playerAnimType screecher, stance prone
		{
			torso pb_rifle_prone_screecher_struggle
		}
		playerAnimType screecher, stance crouch
		{
			torso pb_rifle_crouch_screecher_struggle
		}
		playerAnimType screecher
		{
			torso pb_rifle_stand_screecher_struggle
		}
		// RADIO (perk bottle)
 		playerAnimType radio
 		{
 			torso p_zombie_perkacola_drink weaponTimeScale blendOutTime 48
 		}
		// TABLET
		playerAnimType tablet, stance prone
		{
			torso pt_bowie_prone_putaway
			//both pb_tablet_prone_idle
		}
		playerAnimType tablet, stance crouch
		{
			torso pt_bowie_crouch_putaway
			//both pb_tablet_crouch_idle
		}
		playerAnimType tablet
		{
			torso pt_bowie_stand_putaway
			//torso pt_dw_full_putaway
			//both pb_tablet_stand_idle
		}
		// REVIVER
		playerAnimType reviver, stance prone
		{
			torso p_prone_revive_reviving
		}
		playerAnimType reviver, stance crouch
		{
		 	torso p_crouch_revive_reviving
		}
		playerAnimType reviver
		{
			torso p_revive_reviving
		}
		// HATCHET
		playerAnimType hatchet, stance prone
		{
			both pb_tomahawk_prone_idle
		}
		playerAnimType hatchet, stance crouch
		{
			both pb_tomahawk_crouch_idle
		}
		playerAnimType hatchet
		{
			both pb_tomahawk_stand_idle
		}
		// RIOTSHIELD
		playerAnimType riotshield, weapon_position raised, stance crouch
		{
			both pb_riotshield_crouch_deploy_idle
		}
		playerAnimType riotshield, weapon_position raised
		{
			both pb_riotshield_stand_deploy_idle
		}
		playerAnimType riotshield, stance crouch
		{
			both pb_riotshield_crouch_idle
		}
		playerAnimType riotshield
		{
			both pb_riotshield_stand_idle
		}
		// BRIEFCASE BOMB
		playerAnimType briefcase, stance prone
		{
			both pb_prone_bombplant
		}
		playerAnimType briefcase, stance crouch
		{
			both pb_crouch_bombplant
		}
		playerAnimType briefcase
		{
			both pb_stand_bombplant
		}
		// MINIGUN
		playerAnimType minigun, stance crouch
		{
			both pb_minigun_crouch_idle
		}
		playerAnimType minigun
		{
			both pb_minigun_stand_idle
		}
		// HOLD
		playerAnimType hold, stance prone
		{
			both pb_prone_hold grenadeAnim
		}
		playerAnimType hold, stance crouch
		{
			both pb_crouch_hold_idle grenadeAnim
		}
		playerAnimType hold
		{
			both pb_hold_idle grenadeAnim
		}
		// ZIPLINE
		//playerAnimType zipline
		//{
		//	both pb_zipline_loop
		//}
		// CREATE A CLASS
		//playerAnimType dualwield, cac
		//{
		//	both pb_dw_stand_cac_idle
		//}
		//playerAnimType ballisticknife, cac
		//{
		//	both pb_b_knife_cac_idle
		//}
		//weaponclass mg, cac
		//{
		//	both pb_lmg_stand_cac_idle
		//}
		//weaponclass spread, cac
		//{
		//	both pb_shot_stand_cac_idle
		//}
		//playerAnimType m203, cac // China lake
		//{
		//	both pb_shot_stand_cac_idle
		//}
		//weaponclass smg, cac
		//{
		//	both pb_uzi_stand_cac_idle
		//}
		//playerAnimType sniper AND rearclipsniper, cac
		//{
		//	both pb_sniper_stand_cac_idle
		//}
		//weaponclass rifle, cac
		//{
		//	both pb_rifle_stand_cac_idle
		//}
		//weaponclass pistol, cac
		//{
		//	both pb_pistol_stand_cac_idle
		//}
		//weaponclass rocketlauncher, cac
		//{
		//	both pb_rpg_stand_cac_idle
		//}
		//BALLISTIC KNIFE
		playerAnimType ballisticknife, stance prone
		{
			both pb_b_knife_prone_idle
		}
		playerAnimType ballisticknife, stance crouch
		{
			both pb_b_knife_crouch_idle
		}
		playerAnimType ballisticknife
		{
			both pb_b_knife_stand_idle
		}
		//SINGLE KNIFE
		playerAnimType singleknife AND none, stance prone
		{
			both pb_knife_prone_idle
		}
		playerAnimType singleknife AND none, stance crouch
		{
			both pb_knife_crouch_idle
		}
		playerAnimType singleknife AND none
		{
			both pb_knife_stand_idle
		}
		// DUALWIELD
		playerAnimType dualwield, stance prone
		{
			both pb_prone_dw_idle_v1
		}
		playerAnimType dualwield, stance crouch
		{
			both pb_crouch_dw_idle_v1
		}
		playerAnimType dualwield
		{
			both pb_dw_botharms_idle_v1
		}
		// STAFF
		playerAnimType staff, stance prone
		{
			both pb_staff_prone_idle
		}
		playerAnimType staff, stance crouch
		{
			both pb_staff_crouch_idle
		}
		playerAnimType staff
		{
			both pb_staff_stand_idle
		}
		// PISTOL
		weaponclass pistol AND pistol_spread, weapon_position ads, stance prone
		{
			both pb_prone_aim_ads_pistol
		}
		weaponclass pistol AND pistol_spread, stance prone
		{
			both pb_prone_aim_pistol
		}
		weaponclass pistol AND pistol_spread, weapon_position ads, stance crouch
		{
			both pb_crouch_ads_pistol
		}
		weaponclass pistol AND pistol_spread, stance crouch
		{
			both pb_crouch_alert_pistol
		}
		weaponclass pistol AND pistol_spread, weapon_position ads
		{
			both pb_stand_ads_pistol
		}
		weaponclass pistol AND pistol_spread
		{
			both pb_stand_alert_pistol
		}
		// RPG
		weaponclass rocketlauncher, stance prone
  		{
   			both pb_prone_aim_RPG
  		}
		weaponclass rocketlauncher, weapon_position ads, stance crouch
		{
   			both pb_crouch_ads_RPG
		}
  		weaponclass rocketlauncher, stance crouch
		{
   			both pb_crouch_alert_RPG
  		}
		weaponclass rocketlauncher, weapon_position ads
		{
			both pb_stand_ads_RPG
		}
		weaponclass rocketlauncher
		{
			both pb_stand_alert_RPG
		}
		// GRENADE
		weaponclass grenade, playerAnimType grenadeonly, stance prone
		{
			both pb_grenade_prone_idle grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, stance crouch
		{
			both pb_grenade_crouch_idle grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly
		{
			both pb_grenade_stand_idle grenadeAnim
		}
		weaponclass grenade, playerAnimType riotshield
		{
			both pb_riotshield_pullpin_grenade
		}
		// DEFAULT
		weapon_position ads, stance prone
		{
			both pb_prone_aim_ads
		}
		stance prone
		{
			both pb_prone_aim
		}
		weapon_position ads, stance crouch
		{
			both pb_crouch_ads
		}
		stance crouch // two handed rifle type weapon
		{
			both pb_crouch_alert
		}
		weapon_position ads
		{
			both pb_stand_ads
		}
		perk female
		{
			both pb_fem_rifle_stand_idle
		}
		default // two handed rifle type weapon
		{
			both pb_stand_alert
		}
	}

// STUMBLE
	stumble
	{
		//// RIOTSHIELD
		//playerAnimType riotshield, stance crouch, direction left
		//{
		//	both pb_riot_crouch_stumble_l
		//}
		//playerAnimType riotshield, stance crouch, direction right
		//{
		//	both pb_riot_crouch_stumble_r
		//}
		//playerAnimType riotshield, stance crouch, direction backward
		//{
		//	both pb_riot_crouch_stumble_b
		//}
		//playerAnimType riotshield, stance crouch, direction forward
		//{
		//	both pb_riot_crouch_stumble_f
		//}
		//playerAnimType riotshield, direction left
		//{
		//	both pb_riot_stumble_l
		//}
		//playerAnimType riotshield, direction right
		//{
		//	both pb_riot_stumble_r
		//}
		//playerAnimType riotshield, direction backward
		//{
		//	both pb_riot_stumble_b
		//}
		//playerAnimType riotshield, direction forward
		//{
		//	both pb_riot_stumble_f
		//}
		// TURNED
		playerAnimType turned, direction right
		{
			both pb_zombie_run_right
		}
		playerAnimType turned, direction left
		{
			both pb_zombie_run_left
		}
		playerAnimType turned
		{
			both pb_zombie_run_v1
			both pb_zombie_run_v2
		}

		// HOLD
		playerAnimType hold, direction left
		{
			both pb_hold_stumble_left  grenadeAnim
		}
		playerAnimType hold, direction right
		{
			both pb_hold_stumble_right  grenadeAnim
		}
		playerAnimType hold, direction backward
		{
			both pb_hold_stumble_back  grenadeAnim
		}
		playerAnimType hold, direction forward
		{
			both pb_hold_stumble_forward  grenadeAnim
		}
		// DUAL WIELD
		playerAnimType dualwield AND ballisticknife, direction left
		{
			both pb_dw_stumble_left
		}
		playerAnimType dualwield AND ballisticknife, direction right
		{
			both pb_dw_stumble_right
		}
		playerAnimType dualwield AND ballisticknife, direction backward
		{
			both pb_dw_stumble_back
		}
		playerAnimType dualwield AND ballisticknife, direction forward
		{
			both pb_dw_stumble_forward
		}
		// WEAPONLESS KNIFE
		playerAnimType singleknife, direction left
		{
			both pb_knife_stand_stumble_run_l
		}
		playerAnimType singleknife, direction right
		{
			both pb_knife_stand_stumble_run_r
		}
		playerAnimType singleknife, direction backward
		{
			both pb_knife_stand_stumble_run_b
		}
		playerAnimType singleknife
		{
			both pb_knife_stand_stumble_run_f
		}
		// STAFF
		playerAnimType staff, direction left
		{
			both pb_staff_stumble_left
		}
		playerAnimType staff, direction right
		{
			both pb_staff_stumble_right
		}
		playerAnimType staff, direction backward
		{
			both pb_staff_stumble_back
		}
		playerAnimType staff
		{
			both pb_staff_stumble_forward
		}
		// PISTOL
		weaponclass pistol AND pistol_spread, direction left
		{
			both pb_stumble_pistol_left
		}
		weaponclass pistol AND pistol_spread, direction right
		{
			both pb_stumble_pistol_right
		}
		weaponclass pistol AND pistol_spread, direction backward
		{
			both pb_stumble_pistol_back
		}
		weaponclass pistol AND pistol_spread, direction forward
		{
			both pb_stumble_pistol_forward
		}
		// GRENADE
		weaponclass grenade, direction left, playerAnimType grenadeonly
		{
			both pb_stumble_grenade_left grenadeAnim
		}
		weaponclass grenade, direction right, playerAnimType grenadeonly
		{
			both pb_stumble_grenade_right grenadeAnim
		}
		weaponclass grenade, direction backward, playerAnimType grenadeonly
		{
			both pb_stumble_grenade_back grenadeAnim
		}
		weaponclass grenade, direction forward, playerAnimType grenadeonly
		{
			both pb_stumble_grenade_forward grenadeAnim
		}
		// DEFAULT
		direction left
		{
			both pb_stumble_left
		}
		direction right
		{
			both pb_stumble_right
		}
		direction backward
		{
			both pb_stumble_back
		}
		default
		{
			both pb_stumble_forward
		}
	}

// STUMBLE WALK
	stumble_walk
	{
		// RIOTSHIELD
		//playerAnimType riotshield, direction left
		//{
		//	both pb_riot_stumble_walk_l
		//}
		//playerAnimType riotshield, direction right
		//{
		//	both pb_riot_stumble_walk_r
		//}
		//playerAnimType riotshield, direction backward
		//{
		//	both pb_riot_stumble_walk_b
		//}
		//playerAnimType riotshield, direction forward
		//{
		//	both pb_riot_stumble_walk_f
		//}

		// TURNED
		playerAnimType turned, stance prone
		{
			both pb_zombie_crawl_slow
		}
		playerAnimType turned, stance crouch
		{
			both pb_zombie_crawl_slow
		}
		playerAnimType turned, direction backward
		{
			both pb_zombie_walk_back
		}
		playerAnimType turned
		{
			both pb_zombie_walk_v1
			both pb_zombie_walk_v2
		}

		// HOLD
		playerAnimType hold, direction left
		{
			both pb_hold_stumble_walk_left  grenadeAnim
		}
		playerAnimType hold, direction right
		{
			both pb_hold_stumble_walk_right  grenadeAnim
		}
		playerAnimType hold, direction backward
		{
			both pb_hold_stumble_walk_back  grenadeAnim
		}
		playerAnimType hold, direction forward
		{
			both pb_hold_stumble_walk_forward  grenadeAnim
		}
		// DUAL WIELD
		playerAnimType dualwield AND ballisticknife, direction left
		{
			both pb_dw_stumble_walk_left
		}
		playerAnimType dualwield AND ballisticknife, direction right
		{
			both pb_dw_stumble_walk_right
		}
		playerAnimType dualwield AND ballisticknife, direction backward
		{
			both pb_dw_stumble_walk_back
		}
		playerAnimType dualwield AND ballisticknife, direction forward
		{
			both pb_dw_stumble_walk_forward
		}
		// WEAPONLESS KNIFE
		playerAnimType singleknife, direction left
		{
			both pb_knife_stand_stumble_walk_l
		}
		playerAnimType singleknife, direction right
		{
			both pb_knife_stand_stumble_walk_r
		}
		playerAnimType singleknife, direction backward
		{
			both pb_knife_stand_stumble_walk_b
		}
		playerAnimType singleknife
		{
			both pb_knife_stand_stumble_walk_f
		}
		// STAFF
		playerAnimType staff, direction left
		{
			both pb_staff_stumble_walk_left
		}
		playerAnimType staff, direction right
		{
			both pb_staff_stumble_walk_right
		}
		playerAnimType staff, direction backward
		{
			both pb_staff_stumble_walk_back
		}
		playerAnimType staff
		{
			both pb_staff_stumble_walk_forward
		}
		// PISTOL, GRENADE
		weaponclass pistol AND pistol_spread AND grenade, direction left, playerAnimType grenadeonly
		{
			both pb_stumble_pistol_walk_left
		}
		weaponclass pistol AND pistol_spread AND grenade, direction right, playerAnimType grenadeonly
		{
			both pb_stumble_pistol_walk_right
		}
		weaponclass pistol AND pistol_spread AND grenade, direction backward, playerAnimType grenadeonly
		{
			both pb_stumble_pistol_walk_back
		}
		weaponclass pistol AND pistol_spread AND grenade, direction forward, playerAnimType grenadeonly
		{
			both pb_stumble_pistol_walk_forward
		}
		// DEFAULT
		direction left
		{
			both pb_stumble_walk_left
		}
		direction right
		{
			both pb_stumble_walk_right
		}
		direction backward
		{
			both pb_stumble_walk_back
		}
		default
		{
			both pb_stumble_walk_forward
		}
	}


// STUMBLE SPRINT
	stumble_sprint
	{
		// RIOTSHIELD
		//playerAnimType riotshield
		//{
		//	both pb_riotshield_sprint
		//}
		// DEFAULT
		playerAnimType turned
		{
			both pb_zombie_sprint_v6
			both pb_zombie_sprint_v7
			both pb_zombie_sprint_v8
			both pb_zombie_sprint_v9
			both pb_zombie_sprint_v10
			both pb_zombie_sprint_v11
		}
		default
		{
			both pb_stumble_forward
		}
	}

	shuffle
	{
		direction forward
		{
			both pb_rifle_stand_shuffle_f
		}
		direction backward,
		{
			both pb_rifle_stand_shuffle_b
		}
		direction left
		{
			both pb_rifle_stand_shuffle_l
		}
		direction right
		{
			both pb_rifle_stand_shuffle_r
		}
	}

	walk
	{
		// LASTSTAND
			perk laststand, direction forward
			{
				both pb_laststand_crawl_forward
			}
			perk laststand, direction backward
			{
				both pb_laststand_crawl_back
			}
			perk laststand, direction right
			{
				both pb_laststand_crawl_right
			}
			perk laststand, direction left
			{
				both pb_laststand_crawl_left
			}
		// TURNED
			playerAnimType turned, stance prone
			{
				both pb_zombie_crawl_slow
			}
			playerAnimType turned, stance crouch
			{
				both pb_zombie_crawl_slow
			}
			playerAnimType turned, direction backward
			{
				both pb_zombie_walk_back
			}
			playerAnimType turned
			{
				both pb_zombie_walk_v1
				both pb_zombie_walk_v2
			}
		// RIOTSHIELD
			playerAnimType riotshield, direction left
			{
				both pb_riotshield_walk_left
			}
			playerAnimType riotshield, direction right
			{
				both pb_riotshield_walk_right
			}
			playerAnimType riotshield, direction backward
			{
				both pb_riotshield_walk_back
			}
			playerAnimType riotshield
			{
				both pb_riotshield_walk_forward
			}
		// HOLD
			// Prone
			playerAnimType hold, direction left, stance prone
			{
				both pb_prone_crawl_left_hold  grenadeAnim
			}
			playerAnimType hold, direction right, stance prone
			{
				both pb_prone_crawl_right_hold  grenadeAnim
			}
			playerAnimType hold, direction backward, stance prone
			{
				both pb_prone_crawl_back_hold  grenadeAnim
			}
			playerAnimType hold, stance prone
			{
				both pb_prone_crawl_hold  grenadeAnim
			}
			// Stand
			playerAnimType hold, direction left
			{
				both pb_hold_run_left  grenadeAnim
			}
			playerAnimType hold, direction right
			{
				both pb_hold_run_right  grenadeAnim
			}
			playerAnimType hold, direction backward
			{
				both pb_hold_run_back  grenadeAnim
			}
			playerAnimType hold
			{
				both pb_hold_run  grenadeAnim
			}
		// DUALWIELD
			// Prone
			playerAnimType dualwield AND ballisticknife, direction left, stance prone
			{
				both pb_prone_dw_crawl_left
			}
			playerAnimType dualwield AND ballisticknife, direction right, stance prone
			{
				both pb_prone_dw_crawl_right
			}
			playerAnimType dualwield AND ballisticknife, direction backward, stance prone
			{
				both pb_prone_dw_crawl_back
			}
			playerAnimType dualwield AND ballisticknife, stance prone
			{
				both pb_prone_dw_crawl_forward
			}
		// SINGLE KNIFE
			// Prone
			playerAnimType singleknife AND none, direction left, stance prone
			{
				both pb_knife_prone_crawl_left
			}
			playerAnimType singleknife AND none, direction right, stance prone
			{
				both pb_knife_prone_crawl_right
			}
			playerAnimType singleknife AND none, direction backward, stance prone
			{
				both pb_knife_prone_crawl_back
			}
			playerAnimType singleknife AND none, stance prone
			{
				both pb_knife_prone_crawl_forward
			}
		// Stand
			playerAnimType dualwield, direction left
			{
				both pb_dw_walk_left
			}
			playerAnimType dualwield, direction right
			{
				both pb_dw_walk_right
			}
			playerAnimType dualwield, direction backward
			{
				both pb_dw_walk_back
			}
			playerAnimType dualwield
			{
				both pb_dw_walk_forward
			}
		// BALLISTIC KNIFE
			playerAnimType ballisticknife, direction left
			{
				both pb_b_knife_walk_left
			}
			playerAnimType ballisticknife, direction right
			{
				both pb_b_knife_walk_right
			}
			playerAnimType ballisticknife, direction backward
			{
				both pb_b_knife_walk_back
			}
			playerAnimType ballisticknife
			{
				both pb_b_knife_walk_forward
			}
		// SINGLE KNIFE
			playerAnimType singleknife AND none, direction left
			{
				both pb_knife_walk_left
			}
			playerAnimType singleknife AND none, direction right
			{
				both pb_knife_walk_right
			}
			playerAnimType singleknife AND none, direction backward
			{
				both pb_knife_walk_back
			}
			playerAnimType singleknife AND none
			{
				both pb_knife_walk_forward
			}
		// MINIGUN
			// Stand
			playerAnimType minigun, direction left
			{
				both pb_minigun_stand_walk_left
			}
			playerAnimType minigun, direction right
			{
				both pb_minigun_stand_walk_right
			}
			playerAnimType minigun, direction backward
			{
				both pb_minigun_stand_walk_back
			}
			playerAnimType minigun
			{
				both pb_minigun_stand_walk
			}
		// STAFF
			// Prone
			playerAnimType staff, direction left, stance prone
			{
				both pb_staff_prone_crawl_l
			}
			playerAnimType staff, direction right, stance prone
			{
				both pb_staff_prone_crawl_r
			}
			playerAnimType staff, direction backward, stance prone
			{
				both pb_staff_prone_crawl_b
			}
			playerAnimType staff, stance prone
			{
				both pb_staff_prone_crawl_f
			}
			// Crouch
			playerAnimType staff, direction left, stance crouch
			{
				both pb_staff_crouch_walk_l
			}
			playerAnimType staff, direction right, stance crouch
			{
				both pb_staff_crouch_walk_r
			}
			playerAnimType staff, direction backward, stance crouch
			{
				both pb_staff_crouch_walk_b
			}
			playerAnimType staff, stance prone
			{
				both pb_staff_crouch_walk_f
			}
			// Stand
			playerAnimType staff, direction left
			{
				both pb_staff_stand_walk_l
			}
			playerAnimType staff, direction right
			{
				both pb_staff_stand_walk_r
			}
			playerAnimType staff, direction backward
			{
				both pb_staff_stand_walk_b
			}
			playerAnimType staff
			{
				both pb_staff_stand_walk_f
			}
		// RPG
			// Prone
			weaponclass rocketlauncher, direction left, stance prone
			{
				both pb_rpg_prone_crawl_left
			}
			weaponclass rocketlauncher, direction right, stance prone
			{
				both pb_rpg_prone_crawl_right
			}
			weaponclass rocketlauncher, direction backward, stance prone
			{
				both pb_rpg_prone_crawl_backward
			}
			weaponclass rocketlauncher, stance prone
			{
				both pb_rpg_prone_crawl_forward
			}
			// Crouch
			weaponclass rocketlauncher, direction left, stance crouch
			{
				both pb_crouch_walk_left_RPG
			}
			weaponclass rocketlauncher, direction right, stance crouch
			{
				both pb_crouch_walk_right_RPG
			}
			weaponclass rocketlauncher, direction backward, stance crouch
			{
				both pb_crouch_walk_back_RPG
			}
			weaponclass rocketlauncher, stance crouch
			{
				both pb_crouch_walk_forward_RPG
			}
			// Stand
			weaponclass rocketlauncher, direction left
			{
				both pb_walk_left_RPG_ads
			}
			weaponclass rocketlauncher, direction right
			{
				both pb_walk_right_RPG_ads
			}
			weaponclass rocketlauncher, direction backward
			{
				both pb_walk_back_RPG_ads
			}
			weaponclass rocketlauncher
			{
				both pb_walk_forward_RPG_ads
			}
		// PISTOL
			// Prone
			weaponclass pistol AND pistol_spread, direction left, stance prone
			{
				both pb_prone_pistol_crawl_left
			}
			weaponclass pistol AND pistol_spread, direction right, stance prone
			{
				both pb_prone_pistol_crawl_right
			}
			weaponclass pistol AND pistol_spread, direction backward, stance prone
			{
				both pb_prone_crawl_pistol_back
			}
			weaponclass pistol AND pistol_spread, stance prone
			{
				both pb_prone_crawl_pistol
			}
			// Crouch
			weaponclass pistol AND pistol_spread, direction left, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_walk_left_pistol
			}
			weaponclass pistol AND pistol_spread, direction right, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_walk_right_pistol
			}
			weaponclass pistol AND pistol_spread, direction backward, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_walk_back_pistol
			}
			weaponclass pistol AND pistol_spread, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_walk_forward_pistol
			}
			// Stand
			weaponclass pistol AND pistol_spread, direction left
			{
				both pb_combatwalk_left_loop_pistol
			}
			weaponclass pistol AND pistol_spread, direction right
			{
				both pb_combatwalk_right_loop_pistol
			}
			weaponclass pistol AND pistol_spread, direction backward
			{
				both pb_combatwalk_back_loop_pistol
			}
			weaponclass pistol AND pistol_spread
			{
				both pb_combatwalk_forward_loop_pistol
			}
		// GRENADE
			// Prone
			weaponclass grenade, direction left, playerAnimType grenadeonly, stance prone
			{
				both pb_prone_grenade_crawl_left grenadeAnim
			}
			weaponclass grenade, direction right, playerAnimType grenadeonly, stance prone
			{
				both pb_prone_grenade_crawl_right grenadeAnim
			}
			weaponclass grenade, direction backward, playerAnimType grenadeonly, stance prone
			{
				both pb_prone_grenade_crawl_back grenadeAnim
			}
			weaponclass grenade, playerAnimType grenadeonly, stance prone
			{
				both pb_prone_grenade_crawl grenadeAnim
			}
			// Stand
			weaponclass grenade, direction left, playerAnimType grenadeonly
			{
				both pb_combatrun_left_loop_grenade grenadeAnim
			}
			weaponclass grenade, direction right, playerAnimType grenadeonly
			{
				both pb_combatrun_right_loop_grenade grenadeAnim
			}
			weaponclass grenade, direction backward, playerAnimType grenadeonly
			{
				both pb_combatrun_back_loop_grenade grenadeAnim
			}
			weaponclass grenade, playerAnimType grenadeonly
			{
				both pb_combatrun_forward_loop_stickgrenade grenadeAnim
			}
		// DEFAULT
			// Prone
			direction left, stance prone
			{
				both pb_prone_crawl_left
			}
			direction right, stance prone
			{
				both pb_prone_crawl_right
			}
			direction backward, stance prone
			{
				both pb_prone_crawl_back
			}
			direction forward, stance prone
			{
				both pb_prone_crawl
			}
			// Crouch
			direction left, stance crouch
			{
				both pb_crouch_shoot_run_left
			}
			direction right, stance crouch
			{
				both pb_crouch_shoot_run_right
			}
			direction backward, stance crouch
			{
				both pb_crouch_shoot_run_back
			}
			direction forward, stance crouch // two handed rifle type weapon
			{
				both pb_crouch_shoot_run_forward
			}
			// Stand
			direction left
			{
				both pb_stand_shoot_walk_left
			}
			direction right
			{
				both pb_stand_shoot_walk_right
			}
			direction backward
			{
				both pb_stand_shoot_walk_back
			}
			default // two handed rifle type weapon
			{
				both pb_stand_shoot_walk_forward
			}
	}

	sprint
	{
		// TURNED
		playerAnimType turned
		{
			//both pb_zombie_sprint_fast
			both pb_zombie_sprint_v6
			both pb_zombie_sprint_v7
			both pb_zombie_sprint_v8
			both pb_zombie_sprint_v9
			both pb_zombie_sprint_v10
			both pb_zombie_sprint_v11
		}
		playerAnimType riotshield
		{
			both pb_riotshield_sprint
		}
		// HOLD
		playerAnimType hold
		{
			both pb_sprint_hold  grenadeAnim blendOutTime 200
		}
		// DUALWIELD
		playerAnimType dualwield AND ballisticknife
		{
			both pb_dw_sprint blendOutTime 200
		}
		// SINGLE KNIFE
		playerAnimType singleknife AND none
		{
 			both pb_knife_sprint blendOutTime 200
		}
		// STAFF
		playerAnimType staff
		{
			both pb_staff_stand_sprint blendOutTime 200
		}
		// RPG
		weaponclass rocketlauncher
		{
 			both pb_sprint_RPG blendOutTime 200
		}
		// PISTOL
		weaponclass pistol AND pistol_spread
		{
			both pb_sprint_pistol blendOutTime 200
		}
		// SMG
		weaponclass smg
		{
			both pb_smg_sprint blendOutTime 200
		}
		// MG
		weaponclass mg
		{
			both pb_lmg_sprint blendOutTime 200
		}
		// GRENADE
		weaponclass grenade, playerAnimType grenadeonly
		{
			both pb_grenade_sprint blendOutTime 200
		}
		default
		{
			both pb_sprint blendOutTime 200
		}
	}

	//swim
	//{
	//	// DEFAULT
	//	movestatus stationary
	//	{
	//		both p_swim_tread
	//	}
	//	direction left
	//	{
	//		both p_swim_left
	//	}
	//	direction right
	//	{
	//		both p_swim_right
	//	}
	//	direction backward
	//	{
	//		both p_swim_tread
	//	}
	//	default
	//	{
	//		both p_swim_forward
	//	}
	//}

	run
	{
		// LASTSTAND
			perk laststand, direction forward
			{
				both pb_laststand_crawl_forward
			}
			perk laststand, direction backward
			{
				both pb_laststand_crawl_back
			}
			perk laststand, direction right
			{
				both pb_laststand_crawl_right
			}
			perk laststand, direction left
			{
				both pb_laststand_crawl_left
			}
		// TURNED
			playerAnimType turned, direction right
			{
				both pb_zombie_run_right
			}
			playerAnimType turned, direction left
			{
				both pb_zombie_run_left
			}
			playerAnimType turned
			{
				both pb_zombie_run_v1
				both pb_zombie_run_v2
			}
		// RIOTSHIELD
			playerAnimType riotshield, direction left, stance crouch
			{
				both pb_riotshield_crouch_walk_l
			}
			playerAnimType riotshield, direction right, stance crouch
			{
				both pb_riotshield_crouch_walk_r
			}
			playerAnimType riotshield, direction backward, stance crouch
			{
				both pb_riotshield_crouch_walk_b
			}
			playerAnimType riotshield, stance crouch
			{
				both pb_riotshield_crouch_walk_f
			}
			playerAnimType riotshield, direction backward
			{
				both pb_riotshield_run_back
			}
			playerAnimType riotshield, direction forward
			{
				both pb_riotshield_run_forward
			}
			playerAnimType riotshield, direction left
			{
				both pb_riotshield_run_left
			}
			playerAnimType riotshield, direction right
			{
				both pb_riotshield_run_right
			}
		// HOLD
			// Crouch
			playerAnimType hold, direction left, stance crouch
			{
				both pb_crouch_hold_run_left  grenadeAnim
			}
			playerAnimType hold, direction right, stance crouch
			{
				both pb_crouch_hold_run_right  grenadeAnim
			}
			playerAnimType hold, direction backward, stance crouch
  			{
   				both pb_crouch_hold_run_back  grenadeAnim
  			}
			playerAnimType hold, stance crouch
			{
				both pb_crouch_hold_run  grenadeAnim
			}
			// Stand
			playerAnimType hold, direction left
			{
				both pb_hold_run_left  grenadeAnim
			}
			playerAnimType hold, direction right
			{
				both pb_hold_run_right  grenadeAnim
			}
			playerAnimType hold, direction backward
			{
				both pb_hold_run_back  grenadeAnim
			}
			playerAnimType hold
			{
				both pb_hold_run  grenadeAnim
			}
		// DUALWIELD
			// Crouch
			playerAnimType dualwield, direction left, stance crouch
			{
				both pb_crouch_dw_run_left
			}
			playerAnimType dualwield, direction right, stance crouch
			{
				both pb_crouch_dw_run_right
			}
			playerAnimType dualwield, direction backward, stance crouch
			{
				both pb_crouch_dw_run_back
			}
			playerAnimType dualwield, stance crouch
			{
				both pb_crouch_dw_run_forward
			}
			// Stand
			playerAnimType dualwield, direction left
			{
				both pb_dw_run_left
			}
			playerAnimType dualwield, direction right
			{
				both pb_dw_run_right
			}
			playerAnimType dualwield, direction backward
			{
				both pb_dw_run_back
			}
			playerAnimType dualwield, slope up
			{
				both pb_dw_stand_run_slopeup
			}
			playerAnimType dualwield, slope down
			{
				both pb_dw_stand_run_slopedown
			}
			playerAnimType dualwield
			{
				both pb_dw_run_forward
			}
		// BALLISTIC KNIFE
			// Crouch
			playerAnimType ballisticknife, direction left, stance crouch
			{
				both pb_b_knife_crouch_run_left
			}
			playerAnimType ballisticknife, direction right, stance crouch
			{
				both pb_b_knife_crouch_run_right
			}
			playerAnimType ballisticknife, direction backward, stance crouch
			{
				both pb_b_knife_crouch_run_back
			}
			playerAnimType ballisticknife, stance crouch
			{
				both pb_b_knife_crouch_run_forward
			}
			// Stand
			playerAnimType ballisticknife, direction left
			{
				both pb_b_knife_run_left
			}
			playerAnimType ballisticknife, direction right
			{
				both pb_b_knife_run_right
			}
			playerAnimType ballisticknife, direction backward
			{
				both pb_b_knife_run_back
			}
			playerAnimType ballisticknife
			{
				both pb_b_knife_run_forward
			}
		// SINGLE KNIFE
			// Crouch
			playerAnimType singleknife AND none, direction left, stance crouch
			{
				both pb_knife_crouch_run_left
			}
			playerAnimType singleknife AND none, direction right, stance crouch
			{
				both pb_knife_crouch_run_right
			}
			playerAnimType singleknife AND none, direction backward, stance crouch
			{
				both pb_knife_crouch_run_back
			}
			playerAnimType singleknife AND none, stance crouch
			{
				both pb_knife_crouch_run_forward
			}
			// Stand
			playerAnimType singleknife AND none, direction left
			{
				both pb_knife_run_left
			}
			playerAnimType singleknife AND none, direction right
			{
				both pb_knife_run_right
			}
			playerAnimType singleknife AND none, direction backward
			{
				both pb_knife_run_back
			}
			playerAnimType singleknife AND none
			{
				both pb_knife_run_forward
			}
		// MINIGUN
			// Crouch
			playerAnimType minigun, direction left, stance crouch
			{
				both pb_minigun_crouch_run_left
			}
			playerAnimType minigun, direction right, stance crouch
			{
				both pb_minigun_crouch_run_right
			}
			playerAnimType minigun, direction backward, stance crouch
			{
				both pb_minigun_crouch_run_back
			}
			playerAnimType minigun, stance crouch
			{
				both pb_minigun_crouch_run_forward
			}
			// Stand
			playerAnimType minigun, direction left
			{
				both pb_minigun_stand_run_left
			}
			playerAnimType minigun, direction right
			{
				both pb_minigun_stand_run_right
			}
			playerAnimType minigun, direction backward
			{
				both pb_minigun_stand_run_back
			}
			playerAnimType minigun
			{
				both pb_minigun_stand_run
			}
		// STAFF
			// Crouch
			playerAnimType staff, direction left, stance crouch
			{
				both pb_staff_crouch_run_l
			}
			playerAnimType staff, direction right, stance crouch
			{
				both pb_staff_crouch_run_r
			}
			playerAnimType staff, direction backward, stance crouch
			{
				both pb_staff_crouch_run_b
			}
			playerAnimType staff, stance crouch
			{
				both pb_staff_crouch_run_f
			}
			// Stand
			playerAnimType staff, direction left
			{
				both pb_staff_stand_run_l
			}
			playerAnimType staff, direction right
			{
				both pb_staff_stand_run_r
			}
			playerAnimType staff, direction backward
			{
				both pb_staff_stand_run_b
			}
			playerAnimType staff
			{
				both pb_staff_stand_run_f
			}
		// RPG
			// Crouch
			weaponclass rocketlauncher, direction left, stance crouch
			{
				both pb_crouch_run_left_RPG
			}
			weaponclass rocketlauncher, direction right, stance crouch
			{
				both pb_crouch_run_right_RPG
			}
			weaponclass rocketlauncher, direction backward, stance crouch
			{
				both pb_crouch_run_back_RPG
			}
			weaponclass rocketlauncher, stance crouch
			{
				both pb_crouch_run_forward_RPG
			}
			// Stand
			weaponclass rocketlauncher, direction left
			{
				both pb_combatrun_left_RPG
			}
			weaponclass rocketlauncher, direction right
			{
				both pb_combatrun_right_RPG
			}
			weaponclass rocketlauncher, direction backward
			{
				both pb_combatrun_back_RPG
			}
			weaponclass rocketlauncher
			{
				both pb_combatrun_forward_RPG
			}
		// PISTOL
			// Crouch
			weaponclass pistol AND pistol_spread, direction left, stance crouch
			{
				both pb_crouch_run_left_pistol
			}
			weaponclass pistol AND pistol_spread, direction right, stance crouch
			{
				both pb_crouch_run_right_pistol
			}
			weaponclass pistol AND pistol_spread, direction backward, stance crouch
			{
				both pb_crouch_run_back_pistol
			}
			weaponclass pistol AND pistol_spread, stance crouch
			{
				both pb_crouch_run_forward_pistol
			}
			// Stand
			weaponclass pistol AND pistol_spread, direction left
			{
				both pb_combatrun_left_loop_pistol
			}
			weaponclass pistol AND pistol_spread, direction right
			{
				both pb_combatrun_right_loop_pistol
			}
			weaponclass pistol AND pistol_spread, direction backward
			{
				both pb_combatrun_back_loop_pistol
			}
			weaponclass pistol AND pistol_spread, slope up
			{
				both pb_pistol_stand_run_slopeup
			}
			weaponclass pistol AND pistol_spread, slope down
			{
				both pb_pistol_stand_run_slopedown
			}
			weaponclass pistol AND pistol_spread
			{
				both pb_pistol_run_fast
			}
		// GRENADE
			// Crouch
			weaponclass grenade, direction left, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_run_left_grenade grenadeAnim
			}
			weaponclass grenade, direction right, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_run_right_grenade grenadeAnim
			}
			weaponclass grenade, direction backward, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_run_back_grenade grenadeAnim
			}
			weaponclass grenade, playerAnimType grenadeonly, stance crouch
			{
				both pb_crouch_run_forward_grenade grenadeAnim
			}
			// Stand
			weaponclass grenade, direction left, playerAnimType grenadeonly
			{
				both pb_combatrun_left_loop_grenade grenadeAnim
			}
			weaponclass grenade, direction right, playerAnimType grenadeonly
			{
				both pb_combatrun_right_loop_grenade grenadeAnim
			}
			weaponclass grenade, direction backward, playerAnimType grenadeonly
			{
				both pb_combatrun_back_loop_grenade grenadeAnim
			}
			weaponclass grenade, playerAnimType grenadeonly
			{
				both pb_combatrun_forward_loop_stickgrenade grenadeAnim
			}
		// DEFAULT
			// Crouch
			direction left, stance crouch
			{
				both pb_crouch_run_left
			}
			direction right, stance crouch
			{
				both pb_crouch_run_right
			}
			direction backward, stance crouch
			{
				both pb_crouch_run_back
			}
			stance crouch
			{
				both pb_crouch_run_forward
			}
			// Stand
			direction left
			{
				both pb_combatrun_left_loop
			}
			direction right
			{
				both pb_combatrun_right_loop
			}
			direction backward
			{
				both pb_combatrun_back_loop
			}
			slope up
			{
				both pb_rifle_stand_run_slopeup
			}
			slope down
			{
				both pb_rifle_stand_run_slopedown
			}
			default
			{
				both pb_combatrun_forward_loop
			}
	}

	climbup
	{
		// DEFAULT
		default
		{
			// Can't play the chicken dance here as a temp because it has no movement speed
			both pb_climbup
		}
	}
	climbdown
	{
		// DEFAULT
		default
		{
			// Can't play the chicken dance here as a temp because it has no movement speed
			both pb_climbdown
		}
	}

	turnright
	{
		// TURNED
		playerAnimType turned
		{
			both pb_zombie_stand_turn_r90
		}
		// LAST STAND
		perk laststand
		{
			both pb_laststand_turn_r90
		}
		// NONE
		playerAnimType briefcase, stance prone
		{
			both pb_briefcase_prone_turn_r90
		}
		playerAnimType briefcase, stance crouch
		{
			both pb_briefcase_crouch_turn_r90
		}
		playerAnimType briefcase
		{
			both pb_briefcase_stand_turn_r90
		}
		playerAnimType zipline
		{
			both pb_zipline_loop
		}
		// RIOTSHIELD
		playerAnimType riotshield, stance crouch
		{
			both pb_riotshield_crouch_turn_90r
		}
		playerAnimType riotshield
		{
			both pb_riotshield_stand_turn_90r
		}
		// HOLD
		playerAnimType hold, stance prone
		{
			both pb_hold_prone_turn_90right  grenadeAnim
		}
		playerAnimType hold, stance crouch
		{
			both pb_hold_crouchturn_90right  grenadeAnim
		}
		playerAnimType hold
		{
			both pb_hold_turn_90right  grenadeAnim
		}
 		// RADIO
 		playerAnimType radio
 		{
 			torso p_zombie_perkacola_drink weaponTimeScale blendOutTime 48
 		}
		// TABLET
		playerAnimType tablet, stance prone
		{
			torso pt_bowie_prone_putaway
		}
		playerAnimType tablet, stance crouch
		{
			torso pt_bowie_crouch_putaway
		}
		playerAnimType tablet
		{
			torso pt_bowie_stand_putaway
		}
		// TABLET
//		playerAnimType tablet, stance prone
//		{
//			both pb_tablet_prone_idle
//		}
//		playerAnimType tablet, stance crouch
//		{
//			both pb_tablet_crouch_idle
//		}
//		playerAnimType tablet
//		{
//			both pb_tablet_stand_idle
//		}
		// REMOTE CONTROL
//		playerAnimType remotecontrol, stance prone
//		{
//			both pb_rc_prone_idle
//		}
//		playerAnimType remotecontrol, stance crouch
//		{
//			both pb_rc_crouch_idle
//		}
//		playerAnimType remotecontrol
//		{
//			both pb_rc_stand_idle
//		}
		// DUAL WIELD
		playerAnimType dualwield AND ballisticknife, stance prone
		{
			both pb_dw_prone_turn_90right
		}
		playerAnimType dualwield AND ballisticknife, stance crouch
		{
			both pb_dw_crouchturn_90right
		}
		playerAnimType dualwield AND ballisticknife
		{
			both pb_dw_turn_90right
		}
		// SINGLE KNIFE
		playerAnimType singleknife AND none, stance prone
		{
			both pb_knife_prone_turn_90right
		}
		playerAnimType singleknife AND none, stance crouch
		{
			both pb_knife_crouch_turn_90right
		}
		playerAnimType singleknife AND none
		{
			both pb_knife_stand_turn_90right
		}
		// MINIGUN
		playerAnimType minigun, stance crouch
		{
			both pb_minigun_crouch_turn_90right
		}
		playerAnimType minigun
		{
			both pb_minigun_stand_turn_90right
		}
		// STAFF
		playerAnimType staff, stance prone
		{
			both pb_staff_prone_turn_r
		}
		playerAnimType staff, stance crouch
		{
			both pb_staff_crouch_turn_r
		}
		playerAnimType staff
		{
			both pb_staff_stand_turn_r
		}
		// RPG
		weaponclass rocketlauncher, stance prone
		{
			both pb_rpg_prone_turn90R
		}
		weaponclass rocketlauncher, stance crouch
		{
			both pb_rpg_crouch_turn90R
		}
		weaponclass rocketlauncher
		{
			both pb_rpg_stand_turn90R
		}
		// GRENADE
		weaponclass grenade, playerAnimType grenadeonly, stance prone
		{
			both pb_grenade_prone_turn_90right grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, stance crouch
		{
			both pb_grenade_crouchturn_90right grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly
		{
			both pb_grenade_turn_90right grenadeAnim
		}
		// PISTOL
		weaponclass pistol AND pistol_spread, stance prone
		{
			both pb_pistol_prone_turn_90right
		}
		weaponclass pistol AND pistol_spread, stance crouch
		{
			both pb_pistol_crouchturn_90right
		}
		weaponclass pistol AND pistol_spread
		{
			both pb_pistol_turn_90right
		}
		// DEFAULT
		stance prone
		{
			both pb_prone_turn_90right
		}
		stance crouch
		{
			both pb_crouchturn_90right
		}
		perk female
		{
			both pb_fem_rifle_stand_turn_90right
		}
		default
		{
			both pb_turn_90right
		}
	}
	turnleft
	{
		// TURNED
		playerAnimType turned
		{
			both pb_zombie_stand_turn_l90
		}
		// LAST STAND
		perk laststand
		{
			both pb_laststand_turn_l90
		}
		// NONE
		playerAnimType briefcase, stance prone
		{
			both pb_briefcase_prone_turn_l90
		}
		playerAnimType briefcase, stance crouch
		{
			both pb_briefcase_crouch_turn_l90
		}
		playerAnimType briefcase
		{
			both pb_briefcase_stand_turn_l90
		}
		playerAnimType zipline
		{
			both pb_zipline_loop
		}
		// RIOTSHIELD
		playerAnimType riotshield, stance crouch
		{
			both pb_riotshield_crouch_turn_90l
		}
		playerAnimType riotshield
		{
			both pb_riotshield_stand_turn_90l
		}
		// HOLD
		playerAnimType hold, stance prone
		{
			both pb_hold_prone_turn_90left  grenadeAnim
		}
		playerAnimType hold, stance crouch
		{
			both pb_hold_crouchturn_90left  grenadeAnim
		}
		playerAnimType hold
		{
			both pb_hold_turn_90left  grenadeAnim
		}
		// RADIO
		playerAnimType radio
		{
 			torso p_zombie_perkacola_drink weaponTimeScale blendOutTime 48
		}
		// TABLET
		playerAnimType tablet, stance prone
		{
			torso pt_bowie_prone_putaway
		}
		playerAnimType tablet, stance crouch
		{
			torso pt_bowie_crouch_putaway
		}
		playerAnimType tablet
		{
			torso pt_bowie_stand_putaway
		}
		// TABLET
//		playerAnimType tablet, stance prone
//		{
//			both pb_tablet_prone_idle
//		}
//		playerAnimType tablet, stance crouch
//		{
//			both pb_tablet_crouch_idle
//		}
//		playerAnimType tablet
//		{
//			both pb_tablet_stand_idle
//		}
		// REMOTE CONTROL
//		playerAnimType remotecontrol, stance prone
//		{
//			both pb_rc_prone_idle
//		}
//		playerAnimType remotecontrol, stance crouch
//		{
//			both pb_rc_crouch_idle
//		}
//		playerAnimType remotecontrol
//		{
//			both pb_rc_stand_idle
//		}
		// DUAL WIELD
		playerAnimType dualwield AND ballisticknife, stance prone
		{
			both pb_dw_prone_turn_90left
		}
		playerAnimType dualwield AND ballisticknife, stance crouch
		{
			both pb_dw_crouchturn_90left
		}
		playerAnimType dualwield AND ballisticknife
		{
			both pb_dw_turn_90left
		}
		// SINGLE KNIFE
		playerAnimType singleknife AND none, stance prone
		{
			both pb_knife_prone_turn_90left
		}
		playerAnimType singleknife AND none, stance crouch
		{
			both pb_knife_crouch_turn_90left
		}
		playerAnimType singleknife AND none
		{
			both pb_knife_stand_turn_90left
		}
		// MINIGUN
		playerAnimType minigun, stance crouch
		{
			both pb_minigun_crouch_turn_90left
		}
		playerAnimType minigun
		{
			both pb_minigun_stand_turn_90left
		}
		// STAFF
		playerAnimType staff, stance prone
		{
			both pb_staff_prone_turn_l
		}
		playerAnimType staff, stance crouch
		{
			both pb_staff_crouch_turn_l
		}
		playerAnimType staff
		{
			both pb_staff_stand_turn_l
		}
		// RPG
		weaponclass rocketlauncher, stance prone
		{
			both pb_rpg_prone_turn90L
		}
		weaponclass rocketlauncher, stance crouch
		{
			both pb_rpg_crouch_turn90L
		}
		weaponclass rocketlauncher
		{
			both pb_rpg_stand_turn90L
		}
		// GRENADE
		weaponclass grenade, playerAnimType grenadeonly, stance prone
		{
			both pb_grenade_prone_turn_90left grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, stance crouch
		{
			both pb_grenade_crouchturn_90left grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly
		{
			both pb_grenade_turn_90left grenadeAnim
		}
		// PISTOL
		weaponclass pistol AND pistol_spread, stance prone
		{
			both pb_pistol_prone_turn_90left
		}
		weaponclass pistol AND pistol_spread, stance crouch
		{
			both pb_pistol_crouchturn_90left
		}
		weaponclass pistol AND pistol_spread
		{
			both pb_pistol_turn_90left
		}
		// DEFAULT
		stance prone
		{
			both pb_prone_turn_90left
		}
		stance crouch
		{
			both pb_crouchturn_90left
		}
		perk female
		{
			both pb_fem_rifle_stand_turn_90left
		}
		default
		{
			both pb_turn_90left
		}
	}

	//==========
	// PI - DAY : Mantle animations
	mantle_up_57
	{
		//perk fastmantle
		//{
		//	both mp_mantle_up_57_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_up_57
		}
	}
	mantle_up_51
	{
		//perk fastmantle
		//{
		//	both mp_mantle_up_51_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_up_51
		}
	}
	mantle_up_45
	{
		//perk fastmantle
		//{
		//	both mp_mantle_up_45_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_up_45
		}
	}
	mantle_up_39
	{
		//perk fastmantle
		//{
		//	both mp_mantle_up_39_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_up_39
		}
	}
	mantle_up_33
	{
		//perk fastmantle
		//{
		//	both mp_mantle_up_33_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_up_33
		}
	}
	mantle_up_27
	{
		//perk fastmantle
		//{
		//	legs mp_mantle_up_27_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			legs mp_mantle_up_27
		}
	}
	mantle_up_21
	{
		//perk fastmantle
		//{
		//	legs mp_mantle_up_21_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			legs mp_mantle_up_21
		}
	}
	mantle_over_high
	{
		//perk fastmantle
		//{
		//	both mp_mantle_over_high_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_over_high
		}
	}
	mantle_over_mid
	{
		//perk fastmantle
		//{
		//	both mp_mantle_over_mid_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			both mp_mantle_over_mid
		}
	}
	mantle_over_low
	{
		//perk fastmantle
		//{
		//	legs mp_mantle_over_low_fast animrate 2.5
		//}
		// DEFAULT
		default
		{
			legs mp_mantle_over_low
		}
	}

	dtp_move
	{
		// HOLD
		playerAnimType hold
		{
			both pb_hold_dive_prone  grenadeAnim animrate 1
		}
		// DUALWIELD
		playerAnimType dualwield AND ballisticknife
		{
			both pb_dw_dive_prone animrate 1
		}
		// STAFF
		playerAnimType staff
		{
			 both pb_staff_dive2prone animrate 1
		}
		// PISTOL
		weaponclass pistol AND pistol_spread
		{
			both pb_dive_prone_pistol animrate 1
		}
		// RPG
		weaponclass rocketlauncher
		{
			both pb_rpg_dive_prone
		}
		// GRENADE
		weaponclass grenade, playerAnimType grenadeonly
		{
			both pb_grenade_dive_prone animrate 1
		}
		// DEFAULT
		default
		{
			both pb_dive_prone animrate 1
		}
	}

	slide_move
	{
		// DEFAULT
		direction left
		{
			both pb_terrain_slide
		}
		direction right
		{
			both pb_terrain_slide
		}
		default
		{
			both pb_terrain_slide
		}
	}

}

//==========================================================================
// EVENTS
//
// format:
//
// <event description>
// {
//		[DEFAULT / <condition type> [<condition value>], ...]
//		{
//			<both/legs/torso> <animation> [sound <filename>]
//			<both/legs/torso> <animation> [sound <filename>]
//			...
//		}
// }
//
// legend:
//
// <event description>: pain, death, fireweapon, jump, jumpbk, land, dropweapon,
//		raiseweapon, reload, crouch_to_prone, shellshock
//		prone_to_crouch, meleeattack
//
//	NOTE: for gameplay anims (weapons firing, reload, etc) that show no legs movement
//		only the torso should animation from here, leave the legs doing what their
//		locomotive anims want them to do
//

EVENTS

fireweapon
{
	// TURNED
	playerAnimType turned
	{
		torso pt_zombie_attack_right
	}
	playerAnimType riotshield, stance crouch
	{
		torso pt_riotshield_crouch_deploy_fire
	}
	playerAnimType riotshield
	{
		torso pt_riotshield_stand_deploy_fire
	}
	// LASTSTAND
	perk laststand
	{
		torso pt_laststand_fire
	}
	// REVIVER
	playerAnimType reviver
	{
		torso p_revive_reviving
	}
	// DUAL WIELD
	playerAnimType dualwield, movestatus moving
	{
		// play no animations to prevent blend problems
	}
	playerAnimType dualwield, stance prone
	{
		torso pt_prone_dw_botharms_fire
	}
	playerAnimType dualwield, stance crouch
	{
		torso pt_crouch_dw_botharms_fire
	}
	playerAnimType dualwield
	{
		torso pt_dw_botharms_fire
	}
	// M1216
	playerAnimType g11, weaponclass spread, stance stand
	{
		torso pt_m1216_stand_fire
	}
	// HOLD
	playerAnimType hold, stance prone
	{
		torso pt_hold_prone_throw  grenadeAnim
	}
	playerAnimType hold
	{
 		torso pt_hold_throw  grenadeAnim
	}
	// SNIPER - NEEDS INVESTIGATION!
	playerAnimType sniper AND rearclipsniper, stance prone, weapon_position ads
	{
		torso pt_prone_ads_shoot_auto
	}
	playerAnimType sniper AND rearclipsniper, stance prone
	{
		torso pt_rifle_fire_prone
	}
	playerAnimType sniper AND rearclipsniper, movestatus moving
	{
		// Play no special firing animation
	}
	playerAnimType sniper AND rearclipsniper, stance crouch, weapon_position ads
	{
		torso pt_crouch_shoot_ads
	}
	playerAnimType sniper AND rearclipsniper, stance crouch
	{
		torso pt_crouch_shoot
	}
	playerAnimType sniper AND rearclipsniper, weapon_position ads
	{
		torso pt_rifle_fire_ads
	}
	playerAnimType sniper AND rearclipsniper
	{
		torso pt_rifle_fire
	}
	// CHINA LAKE
	playerAnimType m203, stance prone
	{
		torso pt_prone_shoot_auto
	}
	playerAnimType m203
	{
		torso pt_stand_shoot_shotgun
	}
	// NOPUMP
	playerAnimType nopump, stance prone
	{
		torso pt_prone_shoot
	}
	playerAnimType nopump, movestatus moving
	{
		// No special animation
	}
	playerAnimType nopump, stance crouch, weapon_position ads
	{
		torso pt_crouch_shoot_ads
	}
	playerAnimType nopump, stance crouch
	{
		torso pt_crouch_shoot
	}
	playerAnimType nopump, weapon_position ads
	{
		torso pt_stand_shoot_ads
	}
	playerAnimType nopump
	{
		torso pt_stand_shoot
	}
	//BALLISTIC KNIFE
	playerAnimType ballisticknife, stance prone
	{
		torso pt_b_knife_prone_fire
	}
	playerAnimType ballisticknife, stance crouch
	{
		torso pt_b_knife_crouch_fire
	}
	playerAnimType ballisticknife
	{
		torso pt_b_knife_stand_fire
	}
	// HATCHET
	playerAnimType hatchet, stance prone
	{
		torso pt_tomahawk_prone_throw
	}
	playerAnimType hatchet, stance crouch
	{
		torso pt_tomahawk_crouch_throw
	}
	playerAnimType hatchet
	{
		torso pt_tomahawk_stand_throw
	}
	// SAIGA12
	playerAnimType other, weaponclass spread, stance prone, weapon_position ads
	{
		torso pt_prone_ads_shoot
	}
	playerAnimType other, weaponclass spread, stance prone
	{
		torso pt_prone_shoot
	}
	playerAnimType other, weaponclass spread, stance crouch, weapon_position ads
	{
		torso pt_crouch_shoot_ads
	}
	playerAnimType other, weaponclass spread, stance crouch
	{
		torso pt_crouch_shoot
	}
	playerAnimType other, weaponclass spread, weapon_position ads
	{
		torso pt_stand_shoot_ads
	}
	playerAnimType other, weaponclass spread
	{
 		torso pt_stand_shoot
	}
	// OTHER
	weaponclass spread, stance prone
	{
		torso pt_prone_shoot_auto
	}
	weaponclass spread
	{
		torso pt_stand_shoot_shotgun
	}
	// MINIGUN
	playerAnimType minigun, movestatus moving
	{
		// Play no special firing animation
	}
	playerAnimType minigun, stance crouch
	{
		torso pt_minigun_crouch_fire blendTime 200
	}
	playerAnimType minigun
	{
		torso pt_minigun_stand_fire blendTime 200
	}
	// STAFF
	playerAnimType staff, stance prone
	{
		torso pt_staff_prone_fire
	}
	playerAnimType staff, stance crouch
	{
		torso pt_staff_crouch_fire
	}
	playerAnimType staff
	{
		torso pt_staff_stand_fire
	}
	// PISTOLS
	weaponclass pistol AND pistol_spread, stance prone, weapon_position ads
	{
		torso pt_prone_ads_shoot_pistol
	}
	weaponclass pistol AND pistol_spread, stance prone
	{
		torso pt_prone_shoot_pistol
	}
	weaponclass pistol AND pistol_spread, movestatus moving
	{
		// Play no special firing animation
	}
	weaponclass pistol AND pistol_spread, stance crouch, weapon_position ads
	{
		torso pt_crouch_shoot_ads_pistol
	}
	weaponclass pistol AND pistol_spread, stance crouch
	{
		torso pt_crouch_shoot_pistol
	}
	weaponclass pistol AND pistol_spread, weapon_position ads
	{
		torso pt_stand_shoot_ads_pistol
	}
	weaponclass pistol AND pistol_spread
	{
		torso pt_stand_shoot_pistol
	}
	// MG, SMG
	weaponclass autofire, stance prone, weapon_position ads
	{
		torso pt_prone_ads_shoot_auto blendTime 200 duration 150
	}
	weaponclass autofire, stance prone
	{
		torso pt_prone_shoot_auto blendTime 200 duration 150
	}
	weaponclass autofire, movestatus moving
	{
		// Play no special firing animation
	}
	weaponclass autofire, stance crouch, weapon_position ads
	{
		torso pt_crouch_shoot_auto_ads blendTime 200 duration 150
	}
	weaponclass autofire, stance crouch
	{
		torso pt_crouch_shoot_auto blendTime 200 duration 150
	}
	weaponclass autofire, weapon_position ads
	{
		torso pt_stand_shoot_auto_ads blendTime 200 duration 150
	}
	weaponclass autofire
	{
		torso pt_stand_shoot_auto duration 150
	}
	// RPG (assume ads since you can't fire these from the hip)
	weaponclass rocketlauncher, movestatus moving
	{
		// Play no special firing animation
	}
	weaponclass rocketlauncher, stance prone
	{
		torso pt_prone_shoot_RPG
	}
	weaponclass rocketlauncher, stance crouch
	{
		torso pt_stand_shoot_RPG
	}
	weaponclass rocketlauncher
	{
		torso pt_stand_shoot_RPG
	}
	// GRENADE
	weaponclass grenade, stance prone, playerAnimType grenadeonly  // All prone
	{
		torso pt_prone_grenade_throw grenadeAnim blendTime 133
	}
	weaponclass grenade, stance crouch, playerAnimType grenadeonly // Crouch, moving
	{
 		torso pt_crouch_grenade_throw grenadeAnim blendTime 133
	}
	weaponclass grenade, playerAnimType grenadeonly     // Stand, moving
 	{
 		torso pt_grenade_stand_throw blendtime 133 grenadeAnim weaponTimeScale
 	}
	// DEFAULT
	stance prone, weapon_position ads
	{
		torso pt_prone_ads_shoot
	}
	stance prone
	{
		torso pt_prone_shoot
	}
	movestatus moving
	{
		// Play no special firing animation
	}
	stance crouch, weapon_position ads
	{
		torso pt_crouch_shoot_ads
	}
	stance crouch
	{
		torso pt_crouch_shoot
	}
	weapon_position ads
 	{
 		torso pt_stand_shoot_ads
	}
	perk female
	{
		torso pt_fem_rifle_stand_fire
	}
	default
	{
 		torso pt_stand_shoot
	}
}


prone_to_crouch
{
	// NONE
	nextPlayerAnimType briefcase
	{
		both pb_briefcase_prone2crouch allowMovementInterrupt
	}
	playerAnimType riotshield
	{
		both pb_riotshield_prone2crouch
	}
	// HOLD
	nextPlayerAnimType hold, movestatus moving, direction backward
	{
		both pb_hold_prone2crouch  grenadeAnim allowMovementInterrupt
	}
	nextPlayerAnimType hold, movestatus moving
	{
		both pb_hold_prone2crouchrun  grenadeAnim duration 626 blendouttime 33
	}
	nextPlayerAnimType hold
	{
		both pb_hold_prone2crouch  grenadeAnim allowMovementInterrupt
	}
	// DUALWIELD
	nextPlayerAnimType dualwield AND ballisticknife, movestatus moving, direction backward
	{
		both pb_dw_prone2crouch allowMovementInterrupt
	}
	nextPlayerAnimType dualwield AND ballisticknife, movestatus moving
	{
		both pb_dw_prone2crouchrun duration 626 blendouttime 33
	}
	nextPlayerAnimType dualwield AND ballisticknife
	{
		both pb_dw_prone2crouch allowMovementInterrupt
	}
	// STAFF
	nextPlayerAnimType staff, movestatus moving, direction backward
	{
		both pb_staff_prone2crouch allowMovementInterrupt
	}
	nextPlayerAnimType staff, movestatus moving
	{
		both pb_staff_prone2crouchrun duration 626 blendouttime 33
	}
	nextPlayerAnimType staff
	{
		both pb_staff_prone2crouch allowMovementInterrupt
	}
	// RPG
	nextWeaponclass rocketlauncher, movestatus stationary
	{
		both pb_rpg_prone2crouch allowMovementInterrupt
	}
	// GRENADE
	nextWeaponclass grenade, playerAnimType grenadeonly, movestatus moving, direction backward
	{
		both pb_grenade_prone2crouch allowMovementInterrupt
	}
	nextWeaponclass grenade, playerAnimType grenadeonly , movestatus moving
	{
		both pb_grenade_prone2crouchrun duration 626 blendouttime 33
	}
	nextWeaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_prone2crouch allowMovementInterrupt
	}
	// PISTOL
	nextWeaponclass pistol AND pistol_spread, movestatus moving, direction backward
	{
		both pb_prone2crouch_pistol allowMovementInterrupt
	}
	nextWeaponclass pistol AND pistol_spread, movestatus moving
	{
		both pb_prone2crouchrun_pistol duration 626 blendouttime 33
	}
	nextWeaponclass pistol AND pistol_spread
	{
		both pb_prone2crouch_pistol allowMovementInterrupt
	}
	// RIFLE
	nextWeaponclass rifle, movestatus moving, direction backward
	{
		both pb_prone2crouchrun_back duration 700 blendouttime 67
	}
	nextWeaponclass rifle, movestatus moving, direction right
	{
		both pb_prone2crouchrun_right duration 667 blendouttime 67
	}
	nextWeaponclass rifle, movestatus moving, direction left
	{
		both pb_prone2crouchrun_left duration 467 blendouttime 67
	}
	nextWeaponclass rifle, movestatus moving
	{
		both pb_prone2crouchrun duration 600 blendouttime 170
	}
	nextWeaponclass rifle
	{
		both pb_prone2crouch allowMovementInterrupt
	}
	// HOLD
	playerAnimType hold, movestatus moving, direction backward
	{
		both pb_hold_prone2crouch  grenadeAnim allowMovementInterrupt
	}
	playerAnimType hold, movestatus moving
	{
		both pb_hold_prone2crouchrun  grenadeAnim duration 626 blendouttime 33
	}
	playerAnimType hold
	{
		both pb_hold_prone2crouch  grenadeAnim allowMovementInterrupt
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife, movestatus moving, direction backward
	{
		both pb_dw_prone2crouch allowMovementInterrupt
	}
	playerAnimType dualwield AND ballisticknife, movestatus moving
	{
		both pb_dw_prone2crouchrun duration 626 blendouttime 33
	}
	playerAnimType dualwield AND ballisticknife
	{
		both pb_dw_prone2crouch allowMovementInterrupt
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none, movestatus moving, direction backward
	{
		both pb_knife_prone2crouch allowMovementInterrupt
	}
	playerAnimType singleknife AND none, movestatus moving
	{
		both pb_knife_prone2crouchrun duration 626 blendouttime 33
	}
	playerAnimType singleknife AND none
	{
		both pb_knife_prone2crouch allowMovementInterrupt
	}
	// STAFF
	playerAnimType staff
	{
		both pb_staff_prone2crouch allowMovementInterrupt
	}
	// RPG
	weaponclass rocketlauncher, movestatus stationary
	{
		both pb_rpg_prone2crouch allowMovementInterrupt
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly, movestatus moving, direction backward
	{
		both pb_grenade_prone2crouch allowMovementInterrupt
	}
	weaponclass grenade, playerAnimType grenadeonly , movestatus moving
	{
		both pb_grenade_prone2crouchrun duration 626 blendouttime 33
	}
	weaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_prone2crouch allowMovementInterrupt
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, movestatus moving, direction backward
	{
		both pb_prone2crouch_pistol allowMovementInterrupt
	}
	weaponclass pistol AND pistol_spread, movestatus moving
	{
		both pb_prone2crouchrun_pistol duration 626 blendouttime 33
	}
	weaponclass pistol AND pistol_spread
	{
		both pb_prone2crouch_pistol allowMovementInterrupt
	}
	// DEFAULT
	movestatus moving, direction backward
	{
		both pb_prone2crouchrun_back duration 700 blendouttime 67
	}
	movestatus moving, direction right
	{
		both pb_prone2crouchrun_right duration 667 blendouttime 67
	}
	movestatus moving, direction left
	{
		both pb_prone2crouchrun_left duration 467 blendouttime 67
	}
	movestatus moving
	{
		both pb_prone2crouchrun duration 600 blendouttime 170
	}
	default
	{
		both pb_prone2crouch allowMovementInterrupt
	}
}

prone_to_stand
{
	// HOLD
	nextPlayerAnimType hold, movestatus moving
	{
		both pb_hold_prone2sprint  grenadeAnim blendouttime 33
	}
	nextPlayerAnimType hold
	{
		both pb_hold_prone2stand  grenadeAnim allowMovementInterrupt
	}
	// DUALWIELD
	nextPlayerAnimType dualwield AND ballisticknife, movestatus moving
	{
		both pb_dw_prone2sprint blendouttime 33
	}
	nextPlayerAnimType dualwield AND ballisticknife
	{
		both pb_dw_prone2stand allowMovementInterrupt
	}
	// SINGLE KNIFE
	nextPlayerAnimType singleknife AND none, movestatus moving
	{
		both pb_knife_prone2sprint blendouttime 33
	}
	nextPlayerAnimType singleknife AND none
	{
		both pb_knife_prone2stand allowMovementInterrupt
	}
	// STAFF
	nextPlayerAnimType staff, movestatus moving
	{
		both pb_staff_prone2run
	}
	nextPlayerAnimType staff
	{
		both pb_staff_prone2stand allowMovementInterrupt
	}
	// GRENADE
	nextWeaponclass grenade, playerAnimType grenadeonly, movestatus moving
	{
		both pb_grenade_prone2sprint blendouttime 33
	}
	nextWeaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_prone2stand allowMovementInterrupt
	}
	movestatus moving, direction backward
	{
		both pb_prone2crouchrun_back duration 700 blendouttime 67
	}
	// PISTOL
	nextWeaponclass pistol AND pistol_spread, movestatus moving
	{
		both pb_prone2sprint_pistol blendouttime 33
	}
	nextWeaponclass pistol AND pistol_spread
	{
		both pb_prone2stand_pistol allowMovementInterrupt
	}
	// RIFLE
	nextWeaponclass rifle, movestatus moving
	{
		both pb_prone2sprint blendouttime 33
	}
	nextWeaponclass rifle
	{
		both pb_prone2stand allowMovementInterrupt
	}

	// HOLD
	playerAnimType hold, movestatus moving
	{
		both pb_hold_prone2sprint grenadeAnim blendouttime 33
	}
	playerAnimType hold
	{
		both pb_hold_prone2stand  grenadeAnim allowMovementInterrupt
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife, movestatus moving
	{
		both pb_dw_prone2sprint blendouttime 33
	}
	playerAnimType dualwield AND ballisticknife
	{
		both pb_dw_prone2stand allowMovementInterrupt
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none, movestatus moving
	{
		both pb_knife_prone2sprint blendouttime 33
	}
	playerAnimType singleknife AND none
	{
		both pb_knife_prone2stand allowMovementInterrupt
	}
	// STAFF
	playerAnimType staff, movestatus moving
	{
		both pb_staff_prone2sprint
	}
	playerAnimType staff
	{
		both pb_staff_prone2stand allowMovementInterrupt
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly, movestatus moving
	{
		both pb_grenade_prone2sprint blendouttime 33
	}
	weaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_prone2stand allowMovementInterrupt
	}
	movestatus moving, direction backward
	{
		both pb_prone2crouchrun_back duration 700 blendouttime 67
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, movestatus moving
	{
		both pb_prone2sprint_pistol blendouttime 33
	}
	weaponclass pistol AND pistol_spread
	{
		both pb_prone2stand_pistol allowMovementInterrupt
	}
	// DEFAULT
	movestatus moving
	{
		both pb_prone2sprint blendouttime 33
	}
	default
	{
		both pb_prone2stand allowMovementInterrupt
	}
}

prone_to_sprint
{
	// HOLD
	nextPlayerAnimType hold
	{
		both pb_hold_prone2sprint grenadeAnim blendouttime 33
	}
	// DUALWIELD
	nextPlayerAnimType dualwield AND ballisticknife
	{
		both pb_dw_prone2sprint blendouttime 33
	}
	// SINGLE KNIFE
	nextPlayerAnimType singleknife AND none
	{
		both pb_knife_prone2sprint blendouttime 33
	}
	// STAFF
	nextPlayerAnimType staff
	{
		both pb_staff_prone2run blendouttime 33
	}
	// GRENADE
	nextWeaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_prone2sprint blendouttime 33
	}
	// PISTOL
	nextWeaponclass pistol AND pistol_spread
	{
		both pb_prone2sprint_pistol blendouttime 33
	}
	// RIFLE
	nextWeaponclass rifle
	{
		both pb_prone2sprint blendouttime 33
	}
	// HOLD
	playerAnimType hold
	{
		both pb_hold_prone2sprint  grenadeAnim blendouttime 33
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife
	{
		both pb_dw_prone2sprint blendouttime 33
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none
	{
		both pb_knife_prone2sprint blendouttime 33
	}
	// STAFF
	playerAnimType staff
	{
		both pb_staff_prone2run blendouttime 33
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_prone2sprint blendouttime 33
	}
	// PISTOL
	weaponclass pistol AND pistol_spread
	{
		both pb_prone2sprint_pistol blendouttime 33
	}
	// DEFAULT
	default
	{
		both pb_prone2sprint blendouttime 33
	}
}

crouch_to_prone
{
	// NONE
	nextPlayerAnimType briefcase
	{
		both pb_briefcase_crouch2prone
	}
	// HOLD
	nextPlayerAnimType hold
	{
		both pb_hold_crouch2prone  grenadeAnim
	}
	// DUAL WIELD
	nextPlayerAnimType dualwield AND ballisticknife
	{
		both pb_dw_crouch2prone
	}
	// SINGLE KNIFE
	nextPlayerAnimType singleknife AND none
	{
		both pb_knife_crouch2prone
	}
	// STAFF
	nextPlayerAnimType staff
	{
		both pb_staff_crouch2prone
	}
	// RPG
	nextWeaponclass rocketlauncher
	{
		both pb_rpg_crouch2prone
	}
	// GRENADE
	nextWeaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_crouch2prone
	}
	// PISTOL
	nextWeaponclass pistol AND pistol_spread
	{
		both pb_crouch2prone_pistol
	}
	// DEFAULT
	nextWeaponclass rifle
	{
		both pb_crouch2prone
	}
	// HOLD
	playerAnimType hold
	{
		both pb_hold_crouch2prone  grenadeAnim
	}
	// DUAL WIELD
	playerAnimType dualwield AND ballisticknife
	{
		both pb_dw_crouch2prone
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none
	{
		both pb_knife_crouch2prone
	}
	// STAFF
	playerAnimType staff
	{
		both pb_staff_crouch2prone
	}
	// RPG
	weaponclass rocketlauncher
	{
		both pb_rpg_crouch2prone
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_crouch2prone
	}
	// PISTOL
	weaponclass pistol AND pistol_spread
	{
		both pb_crouch2prone_pistol
	}
	// DEFAULT
	default
	{
		both pb_crouch2prone
	}
}

crouch_to_stand
{
	default
	{
		// No Animation
	}
}

stand_to_crouch
{
	default
	{
		// No Animation
	}
}

stand_to_laststand
{
	perk turned
	{
		both pb_zombie_death_v1
		both pb_zombie_death_v2
	}
	default
	{
		both pb_stand2laststand
	}
}

crouch_to_laststand
{
	default
	{
		both pb_crouch2laststand
	}
}

prone_to_laststand
{
	default
	{
		both pb_prone2laststand
	}
}

laststand_to_stand
{
	default
	{
		both pb_laststand2stand blendOutTime 200
	}
}

laststand_to_crouch
{
	default
	{
		both pb_laststand2crouch
	}
}

laststand_to_prone
{
	default
	{
		both pb_laststand2prone
	}
}

meleeattack
{
	// TURNED
	playerAnimType turned
	{
		torso pt_zombie_attack_right
	}
	// GRENADE
	weaponclass grenade, stance prone
	{
		torso pt_grenade_prone_melee_swipe
	}
	weaponclass grenade, stance crouch
	{
		torso pt_grenade_crouch_melee_swipe
	}
	weaponclass grenade
	{
		torso pt_grenade_stand_melee_swipe
	}

	// PISTOL, GRENADE
	weaponclass pistol AND pistol_spread AND grenade, stance prone, playerAnimType grenadeonly
	{
		torso pt_melee_prone_pistol
	}
	weaponclass pistol AND pistol_spread AND grenade
	{
		torso pt_melee_pistol_1 duration 400
		torso pt_melee_pistol_2 duration 350
		torso pt_melee_pistol_3 duration 550
		torso pt_melee_pistol_4 duration 400
	}
	playerAnimType riotshield
	{
		torso pt_riotshield_melee
	}
	// DEFAULT
	stance prone
	{
		torso pt_melee_prone
	}
	stance crouch
	{
		torso pt_melee_crouch_left2left
		torso pt_melee_crouch_left2right
		torso pt_melee_crouch_right2left
	}
	perk female
	{
		torso pt_fem_rifle_stand_knife_swipe
	}
	default
	{
		torso pt_melee_right2right_1 duration 400
		torso pt_melee_right2right_2 duration 400
		torso pt_melee_right2left duration 300
		torso pt_melee_left2left_1 duration 400
		torso pt_melee_left2right duration 300
	}
}

meleeleft
{
	// TURNED
	playerAnimType turned
	{
		torso pt_zombie_attack_left
	}
	// DEFAULT
	stance prone
	{
		torso pt_melee_prone
	}
	stance crouch
	{
		torso pt_melee_crouch_left2left
		torso pt_melee_crouch_left2right
		torso pt_melee_crouch_right2left
	}
	default
	{
		torso pt_melee_right2right_1 duration 400
		torso pt_melee_right2right_2 duration 400
		torso pt_melee_right2left duration 300
		torso pt_melee_left2left_1 duration 400
		torso pt_melee_left2right duration 300
	}
}

knife_melee
{

	// ONE INCH PUNCH
	perk oneinchpunch, playerAnimType hold, stance stand
	{
		torso pt_one_inch_punch_stand_hold
	}
	perk oneinchpunch, playerAnimType staff, stance stand
	{
		torso pt_one_inch_punch_stand_staff
	}
	perk oneinchpunch, stance stand
	{
		torso pt_one_inch_punch_stand
	}
	// TURNED
	playerAnimType turned
	{
		torso pt_zombie_attack_right
	}
	// LASTSTAND
	perk laststand
	{
		torso p_revive_down_melee_swipe
	}
	// GRENADE
	weaponclass grenade, stance prone
	{
		torso pt_grenade_prone_melee_swipe
	}
	weaponclass grenade, stance crouch
	{
		torso pt_grenade_crouch_melee_swipe
	}
	weaponclass grenade
	{
		torso pt_grenade_stand_melee_swipe
	}
	// HOLD
	// *** LDS - NEED TO ADD PRONE ANIMS FOR HOLD WEAPONS
	playerAnimType hold, stance prone
	{
		torso pt_hold_melee_prone  grenadeAnim
	}
	playerAnimType hold
	{
		torso pt_melee_hold_1 grenadeAnim
	}
	// BALLISTIC KNIFE
	playerAnimType ballisticknife, stance prone
	{
		torso pt_b_knife_prone_melee
	}
	playerAnimType ballisticknife, stance crouch
	{
		torso pt_b_knife_crouch_melee
	}
	playerAnimType ballisticknife
	{
		torso pt_b_knife_stand_melee
	}
	// SINGLE KNIFE
	playerAnimType singleknife, stance prone
	{
		torso pt_knife_prone_melee_swipe
	}
	playerAnimType singleknife, stance crouch
	{
		torso pt_knife_crouch_melee_swipe
	}
	playerAnimType singleknife
	{
		torso pt_knife_stand_melee_swipe
	}
	// DUALWIELD
	playerAnimType dualwield, stance prone
	{
		torso pt_dw_prone_melee
	}
	playerAnimType dualwield
	{
		torso pt_dw_stand_melee_swipe blendTime 17 blendOutTime 17
	}
	// STAFF
	playerAnimType staff, stance prone
	{
		torso pt_staff_prone_melee
	}
	playerAnimType staff, stance crouch
	{
		torso pt_staff_crouch_melee
	}
	playerAnimType staff
	{
		torso pt_staff_stand_melee
	}
	// RPG
	weaponclass rocketlauncher, stance prone
	{
		torso p_knife_prone_bazooka_swipe
	}
	weaponclass rocketlauncher, stance crouch
	{
		torso p_knife_crouch_bazooka_swipe
	}
	weaponclass rocketlauncher
	{
		torso p_knife_stand_bazooka_swipe
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, stance prone
	{
		torso p_knife_prone_pistol_swipe
	}
	weaponclass pistol AND pistol_spread, stance crouch
	{
		torso p_knife_crouch_pistol_swipe
	}
	weaponclass pistol AND pistol_spread
	{
		torso p_knife_stand_pistol_swipe
	}
	// DEFAULT
	stance prone
	{
		torso p_knife_prone_rifle_swipe
	}
	stance crouch
	{
		torso p_knife_crouch_rifle_swipe
	}
	perk female
	{
		torso pt_fem_rifle_stand_knife_swipe
	}
	default
	{
		torso p_knife_stand_rifle_swipe
	}
}

knife_melee_charge
{
	// ONE INCH PUNCH
	perk oneinchpunch, playerAnimType hold, stance stand
	{
		both pb_one_inch_punch_charge_hold
	}
	perk oneinchpunch, playerAnimType staff, stance stand
	{
		both pb_one_inch_punch_charge_staff
	}
	perk oneinchpunch, stance stand
	{
		both pb_one_inch_punch_charge
	}
	// TURNED
	playerAnimType turned
	{
		torso pt_zombie_attack_right
	}
	// HOLD
	playerAnimType hold, stance prone
	{
		torso pt_hold_melee_prone grenadeAnim
	}
	playerAnimType hold
	{
		torso pt_melee_hold_2 grenadeAnim
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife, stance prone
	{
		torso pt_dw_prone_melee
	}
	playerAnimType dualwield AND ballisticknife
	{
		torso pt_dw_stand_melee_stick
	}
	// SINGLE KNIFE
	playerAnimType singleknife, stance prone
	{
		torso pt_knife_prone_melee_thrust
	}
	playerAnimType singleknife, stance crouch
	{
		torso pt_knife_crouch_melee_thrust
	}
	playerAnimType singleknife
	{
		torso pt_knife_stand_melee_thrust
	}
	// STAFF
	playerAnimType staff, stance prone
	{
		torso pt_staff_prone_melee_charge
	}
	playerAnimType staff, stance crouch
	{
		torso pt_staff_crouch_melee_charge
	}
	playerAnimType staff
	{
		torso pt_staff_stand_melee_charge
	}
	// RPG
	weaponclass rocketlauncher, stance prone
	{
		torso p_knife_prone_bazooka
	}
	weaponclass rocketlauncher, stance crouch
	{
		torso p_knife_crouch_bazooka
	}
	weaponclass rocketlauncher
	{
		torso p_knife_stand_bazooka
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, stance prone
	{
		torso p_knife_prone_pistol
	}
	weaponclass pistol AND pistol_spread, stance crouch
	{
		torso p_knife_crouch_pistol
	}
	weaponclass pistol AND pistol_spread
	{
		torso p_knife_stand_pistol
	}
	// DEFAULT
	stance prone
	{
		torso p_knife_prone_rifle
	}
	stance crouch
	{
		torso p_knife_crouch_rifle
	}
	default
	{
		torso p_knife_stand_rifle
	}
}

dropweapon
{
	riotshieldnext
	{
		torso pt_putaway2shield_raise weaponTimeScale
	}
	// RIOTSHIELD
	playerAnimType riotshield, stance crouch
	{
		torso pt_riotshield_crouch_putaway weaponTimeScale
	}
	playerAnimType riotshield
	{
		torso pt_riotshield_stand_putaway weaponTimeScale
	}
	// HOLD
	stance prone, playerAnimType hold
	{
		torso pt_satchel_prone_putaway  grenadeAnim weaponTimeScale
	}
	playerAnimType hold
	{
		torso pt_satchel_stand_putaway  grenadeAnim weaponTimeScale
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife, stance prone
	{
		torso pt_prone_dw_putaway weaponTimeScale
	}
	playerAnimType dualwield AND ballisticknife, stance crouch
	{
		torso pt_crouch_dw_putaway weaponTimeScale
	}
	playerAnimType dualwield AND ballisticknife
	{
		torso pt_dw_full_putaway weaponTimeScale
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none, stance prone
	{
		torso pt_knife_prone_putaway weaponTimeScale
	}
	playerAnimType singleknife AND none, stance crouch
	{
		torso pt_knife_crouch_putaway weaponTimeScale
	}
	playerAnimType singleknife AND none
	{
		torso pt_knife_stand_putaway weaponTimeScale
	}
	// BRIEFCASE BOMB
	playerAnimType briefcase, stance prone
	{
		torso pt_rc_prone_putaway weaponTimeScale
	}
	playerAnimType briefcase, stance crouch
	{
		torso pt_rc_crouch_putaway weaponTimeScale
	}
	playerAnimType briefcase
	{
		torso pt_rc_stand_putaway weaponTimeScale
	}
	// MINIGUN
	playerAnimType minigun, stance crouch
	{
		torso pt_minigun_crouch_putaway weaponTimeScale
	}
	playerAnimType minigun
	{
		torso pt_minigun_stand_putaway weaponTimeScale
	}
	// REMOTE CONTROL
//	playerAnimType remotecontrol, stance prone
//	{
//		torso pt_rc_prone_putaway weaponTimeScale
//	}
//	playerAnimType remotecontrol, stance crouch
//	{
//		torso pt_rc_crouch_putaway weaponTimeScale
//	}
//	playerAnimType remotecontrol
//	{
//		torso pt_rc_stand_putaway weaponTimeScale
//	}
	// RADIO
	playerAnimType radio, stance prone
	{
		torso pt_radio_prone_putaway weaponTimeScale blendOutTime 48
	}
	playerAnimType radio, stance crouch
	{
		torso pt_radio_crouch_putaway weaponTimeScale blendOutTime 48
	}
	playerAnimType radio
	{
		torso pt_radio_stand_putaway weaponTimeScale blendOutTime 48
	}
	// TABLET
	playerAnimType tablet, stance prone
	{
		torso pt_tablet_prone_putaway weaponTimeScale blendOutTime 48
	}
	playerAnimType tablet, stance crouch
	{
		torso pt_tablet_crouch_putaway weaponTimeScale blendOutTime 48
	}
	playerAnimType tablet
	{
		torso pt_tablet_stand_putaway weaponTimeScale blendOutTime 48
	}
	// ZIPLINE
	playerAnimType zipline
	{
		torso pb_zipline_release
	}
	// STAFF
	playerAnimType staff, stance prone
	{
		torso pt_staff_prone_putaway weaponTimeScale
	}
	playerAnimType staff, stance crouch
	{
		torso pt_staff_crouch_putaway weaponTimeScale
	}
	playerAnimType staff
	{
		torso pt_staff_stand_putaway weaponTimeScale
	}
	// RPG
	weaponclass rocketlauncher, stance prone
	{
		torso pt_rpg_prone_putaway weaponTimeScale
	}
	weaponclass rocketlauncher
	{
		torso pt_rpg_stand_putaway weaponTimeScale
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, stance prone
	{
		torso pt_pistol_prone_putaway weaponTimeScale
	}
	weaponclass pistol AND pistol_spread, stance crouch
	{
		torso pt_pistol_crouch_putaway weaponTimeScale
	}
	weaponclass pistol AND pistol_spread
	{
		torso pt_pistol_stand_putaway weaponTimeScale
	}
	// DEFAULT
	stance prone
	{
		torso pt_rifle_prone_putaway weaponTimeScale
	}
	stance crouch
	{
		torso pt_rifle_crouch_putaway weaponTimeScale
	}
	default
	{
		torso pt_rifle_stand_putaway weaponTimeScale
	}
}

raiseweapon
{
	// RIOTSHIELD
	playerAnimType riotshield, stance crouch
	{
		torso pt_riotshield_crouch_raise weaponTimeScale
	}
	playerAnimType riotshield
	{
		torso pt_riotshield_stand_raise weaponTimeScale
	}
	// HOLD
	playerAnimType hold, stance prone
	{
		torso pt_satchel_prone_raise  grenadeAnim weaponTimeScale blendTime 125
	}
	playerAnimType hold
	{
		torso pt_satchel_stand_raise  grenadeAnim weaponTimeScale blendTime 125
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife, stance prone
	{
		torso pt_prone_dw_raise weaponTimeScale
	}
	playerAnimType dualwield AND ballisticknife, stance crouch
	{
		torso pt_crouch_dw_raise weaponTimeScale
	}
	playerAnimType dualwield AND ballisticknife
	{
		torso pt_dw_full_pullout weaponTimeScale
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none, stance prone
	{
		torso pt_knife_prone_raise weaponTimeScale
	}
	playerAnimType singleknife AND none, stance crouch
	{
		torso pt_knife_crouch_raise weaponTimeScale
	}
	playerAnimType singleknife AND none
	{
		torso pt_knife_stand_raise weaponTimeScale
	}
	// BRIEFCASE BOMB
	playerAnimType briefcase, stance prone
	{
	}
	playerAnimType briefcase, stance crouch
	{
	}
	playerAnimType briefcase
	{
	}
	// REVIVER
	playerAnimType reviver
	{
		// No animation
	}
	// MINIGUN
	playerAnimType minigun, stance crouch
	{
		torso pt_minigun_crouch_raise weaponTimeScale
	}
	playerAnimType minigun
	{
		torso pt_minigun_stand_raise weaponTimeScale
	}
	// REMOTE CONTROL
//	playerAnimType remotecontrol, stance prone
//	{
//		torso pt_rc_prone_raise weaponTimeScale
//	}
//	playerAnimType remotecontrol, stance crouch
//	{
//		torso pt_rc_crouch_raise weaponTimeScale
//	}
//	playerAnimType remotecontrol
//	{
//		torso pt_rc_stand_raise weaponTimeScale
//	}
	// RADIO
	playerAnimType radio
	{
		torso p_zombie_perkacola_drink
	}
	// TABLET
	playerAnimType tablet, stance prone
	{
		torso pt_tablet_prone_raise weaponTimeScale blendTime 48
	}
	playerAnimType tablet, stance crouch
	{
		torso pt_tablet_crouch_raise weaponTimeScale blendTime 48
	}
	playerAnimType tablet
	{
		torso pt_tablet_stand_raise weaponTimeScale blendTime 48
	}
	// HATCHET
	playerAnimType hatchet, stance prone
	{
		torso pt_tomahawk_prone_pullout
	}
	playerAnimType hatchet, stance crouch
	{
		torso pt_tomahawk_crouch_pullout
	}
	playerAnimType hatchet
	{
		torso pt_tomahawk_stand_pullout
	}
	// ZIPLINE
	playerAnimType zipline
	{
		torso pb_zipline_grab
	}
	// STAFF
	playerAnimType staff, stance prone
	{
		torso pt_staff_prone_raise weaponTimeScale
	}
	playerAnimType staff, stance crouch
	{
		torso pt_staff_crouch_raise weaponTimeScale
	}
	playerAnimType staff
	{
		torso pt_staff_stand_raise weaponTimeScale
	}
	// RPG
	weaponclass rocketlauncher, stance prone
	{
		torso pt_rpg_prone_raise weaponTimeScale
	}
	weaponclass rocketlauncher
	{
		torso pt_rpg_stand_raise weaponTimeScale
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, stance prone
	{
		torso pt_pistol_prone_raise weaponTimeScale
	}
	weaponclass pistol AND pistol_spread, stance crouch
	{
		torso pt_pistol_crouch_raise weaponTimeScale
	}
	weaponclass pistol AND pistol_spread
	{
		torso pt_pistol_stand_raise weaponTimeScale
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly, stance prone
	{
		torso pt_grenade_prone_prime grenadeAnim
	}
	weaponclass grenade, playerAnimType grenadeonly, stance crouch
	{
		torso pt_grenade_crouch_prime grenadeAnim
	}
	weaponclass grenade, playerAnimType grenadeonly
	{
		torso pt_grenade_stand_prime
	}
	// DEFAULT
	stance prone
	{
		torso pt_rifle_prone_raise weaponTimeScale
	}
	stance crouch
	{
		torso pt_rifle_crouch_raise weaponTimeScale
	}
	perk female
	{
		torso pt_fem_rifle_stand_raise
	}
	default
	{
		torso pt_rifle_stand_raise weaponTimeScale
	}
}

//firstraiseweapon
//{
//	// RIOTSHIELD
//	playerAnimType riotshield, stance stand
//	{
//		torso pt_riot_stand_firstraise weaponTimeScale
//	}
//	// DUALWIELD
//	playerAnimType dualwield, stance stand
//	{
//		torso pt_dw_stand_firstraise weaponTimeScale
//	}
//	// BALLISTIC KNIFE
//	playerAnimType ballisticknife, stance stand
//	{
//		torso pt_b_knife_stand_firstraise weaponTimeScale
//	}
//	// SINGLE KNIFE
//	playerAnimType singleknife
//	{
//		torso pt_knife_stand_firstraise weaponTimeScale
//	}
//	playerAnimType minigun, stance stand
//	{
//		torso pt_minigun_stand_firstraise weaponTimeScale
//	}
//	weaponclass rocketlauncher, stance stand
//	{
//		torso pt_rpg_stand_firstraise weaponTimeScale
//	}
//	// REVOLVER
//	weaponclass pistol_spread, stance stand
//	{
//		torso pt_judge_stand_firstraise
//	}
//	// PISTOL
//	weaponclass pistol, stance stand
//	{
//		torso pt_pistol_stand_firstraise weaponTimeScale
//	}
//	// CROSSBOW
//	playerAnimType crossbow, stance stand
//	{
//		torso pt_crossbow_stand_firstraise weaponTimeScale
//	}
//	// SHOTGUN
//	weaponclass spread, stance stand
//	{
//		torso pt_shot_stand_firstraise weaponTimeScale
//	}
//	// SNIPER
//	playerAnimType sniper, stance stand
//	{
//		torso pt_sniper_stand_firstraise weaponTimeScale
//	}
//	// LMG
//	weaponclass mg, stance stand
//	{
//		torso pt_lmg_stand_firstraise weaponTimeScale
//	}
//	// SMG
//	weaponclass smg, stance stand
//	{
//		torso pt_smg_stand_firstraise weaponTimeScale
//	}
//	// RIFLE
//	weaponclass rifle, stance stand
//	{
//		torso pt_rifle_stand_firstraise weaponTimeScale
//	}
//	perk female
//	{
//		torso pt_fem_rifle_stand_firstraise
//	}
//	// DEFAULT
//	default
//	{
//	}
//}

reload
{
	// LASTSTAND
	perk laststand
 	{
   		torso pt_laststand_reload
  	}
  	// BALLISTIC KNIFE
  	playerAnimType ballisticknife, stance prone
	{
		torso pt_b_knife_prone_reload
	}
	playerAnimType ballisticknife, stance crouch
	{
		torso pt_b_knife_crouch_reload
	}
	playerAnimType ballisticknife
	{
		torso pt_b_knife_stand_reload
	}
	// GRIMREAPER ANIM TYPE IS GRENADE LAUNCHER MULTI-NADE RELOAD
	//playerAnimType grimreaper, stance prone
	//{
	//	torso pt_m202_prone_reload
	//}
	//playerAnimType grimreaper, stance crouch
	//{
	//	torso pt_m202_crouch_reload
	//}
	//playerAnimType grimreaper
	//{
	//	torso pt_m202_stand_reload
	//}
	// DUALWIELD
	playerAnimType dualwield, stance prone
	{
		torso pt_prone_dw_botharms_reload
	}
	playerAnimType dualwield, stance crouch
	{
		torso pt_crouch_dw_botharms_reload
	}
	playerAnimType dualwield
	{
		torso pt_dw_botharms_reload
	}
	// CROSSBOW
	playerAnimType crossbow, stance prone
	{
		torso pt_crossbow_prone_reload
	}
	playerAnimType crossbow, stance crouch
	{
		torso pt_crossbow_crouch_reload
	}
	playerAnimType crossbow
	{
		torso pt_crossbow_stand_reload
	}
	// MINIGUN
	playerAnimType minigun, stance crouch
	{
		torso pt_minigun_crouch_reload
	}
	playerAnimType minigun
	{
		torso pt_minigun_stand_reload
	}
	// UNDERBARREL GRENADE LAUNCHER
	playerAnimType m203, stance prone
	{
		torso pt_rifle_prone_reload_gl
	}
	playerAnimType m203, stance crouch
	{
		torso pt_rifle_crouch_reload_gl
	}
	playerAnimType m203
	{
		torso pt_rifle_stand_reload_gl
	}
	// REARCLIP
	playerAnimType rearclip AND rearclipsniper, stance prone
	{
		torso pt_rifle_prone_reload_rearclip
	}
	playerAnimType rearclip AND rearclipsniper, stance crouch
	{
		torso pt_rifle_crouch_reload_rearclip
	}
	playerAnimType rearclip AND rearclipsniper, perk female
	{
		torso pt_fem_rifle_stand_reload_rearclip
	}
	playerAnimType rearclip AND rearclipsniper
	{
		torso pt_rifle_stand_reload_rearclip
	}
	// HANDLECLIP
	playerAnimType handleclip, stance prone
	{
		torso pt_rifle_prone_reload_handleclip
	}
	playerAnimType handleclip, stance crouch
	{
		torso pt_rifle_crouch_reload_handleclip
	}
	playerAnimType handleclip, perk female
	{
		torso pt_fem_rifle_stand_reload_handleclip
	}
	playerAnimType handleclip
	{
		torso pt_rifle_stand_reload_handleclip
	}
	// LMG
	playerAnimType beltfed, stance prone
	{
		torso pt_lmg_prone_reload
	}
	playerAnimType beltfed, stance crouch
	{
		torso pt_lmg_crouch_reload
	}
	playerAnimType beltfed
	{
		torso pt_lmg_stand_reload
	}
	// M1216
	playerAnimType g11, weaponclass spread, stance prone
	{
		torso pt_m1216_prone_reload
	}
	playerAnimType g11, weaponclass spread, stance crouch
	{
		torso pt_m1216_crouch_reload
	}
	playerAnimType g11, weaponclass spread
	{
		torso pt_m1216_stand_reload
	}

	// SAIGA
	playerAnimType other, weaponclass spread, stance prone
	{
		torso pt_reload_prone_auto
	}
	playerAnimType other, weaponclass spread, stance crouch
	{
		torso pt_reload_crouch_rifle
	}
	playerAnimType other, weaponclass spread, perk female
	{
		torso pt_fem_rifle_stand_reload
	}
	playerAnimType other, weaponclass spread
	{
		torso pt_reload_stand_rifle
	}

	// Judge
	weaponclass pistol_spread, stance prone
	{
		torso pt_judge_prone_reload
	}
	weaponclass pistol_spread, stance crouch
	{
		torso pt_judge_crouch_reload
	}
	weaponclass pistol_spread
	{
		torso pt_judge_stand_reload
	}
	// M1216
	playerAnimType g11, weaponclass spread, stance prone
	{
		torso pt_m1216_prone_reload
	}
	playerAnimType g11, weaponclass spread, stance crouch
	{
		torso pt_m1216_crouch_reload
	}
	playerAnimType g11, weaponclass spread
	{
		torso pt_m1216_stand_reload
	}
	// G11
	playerAnimType g11, stance prone
	{
		torso pt_g11_prone_reload
	}
	playerAnimType g11, stance crouch
	{
		torso pt_g11_crouch_reload
	}
	playerAnimType g11
	{
		torso pt_g11_stand_reload
	}
	// STAFF
	playerAnimType staff
	{
		// No reload animation
	}
	// SMG
	weaponclass smg, stance prone
	{
		torso pt_reload_prone_auto
	}
	weaponclass smg, movestatus stationary, stance crouch
	{
		torso pt_reload_stand_auto_mp40
	}
	weaponclass smg, stance crouch
	{
		torso pt_reload_crouchwalk
	}
	weaponclass smg
	{
		torso pt_reload_stand_auto_mp40
	}
	// MG
	weaponclass mg, stance prone
	{
		torso pt_reload_prone_auto
	}
	weaponclass mg, movestatus stationary, stance crouch
	{
		torso pt_reload_crouch_rifle
	}
	weaponclass mg, stance crouch
	{
		torso pt_reload_crouchwalk
	}
	weaponclass mg
	{
		torso pt_reload_stand_auto
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, movestatus stationary, stance crouch
	{
		torso pt_reload_crouch_pistol
	}
	weaponclass pistol AND pistol_spread, stance crouch
	{
		torso pt_reload_crouchwalk_pistol
	}
	weaponclass pistol AND pistol_spread, stance prone
	{
		torso pt_reload_prone_pistol
	}
	weaponclass pistol AND pistol_spread
	{
		torso pt_reload_stand_pistol
	}
	// SPREAD
	weaponclass spread, stance prone
	{
		torso pt_shot_prone_reload
	}
	weaponclass spread, stance crouch
	{
		torso pt_shot_crouch_reload
	}
	weaponclass spread
	{
		torso pt_shot_stand_reload
	}
	// RPG
	weaponclass rocketlauncher, stance prone
 	{
	   	torso pt_reload_prone_RPG
	}
 	weaponclass rocketlauncher
	{
	   	torso pt_reload_stand_RPG
	}
	// DEFAULT
	stance prone
	{
		torso pt_reload_prone_auto
	}
	movestatus stationary, stance crouch
	{
		torso pt_reload_crouch_rifle
	}
	stance crouch
	{
		torso pt_reload_crouch_rifle
	}
	perk female
	{
		torso pt_fem_rifle_stand_reload
	}
	default
	{
		torso pt_reload_stand_rifle
	}
}

run_to_idle
{
	// TURNED
	playerAnimType turned
	{
	}
	playerAnimType minigun, prevdirection backward
	{
		legs pb_minigun_stand_run_b_2_idle duration 5 blendtime 100
	}
	playerAnimType minigun, prevdirection left
	{
		legs pb_minigun_stand_run_l_2_idle duration 5 blendtime 100
	}
	playerAnimType minigun, prevdirection right
	{
		legs pb_minigun_stand_run_r_2_idle duration 5 blendtime 100
	}
	playerAnimType minigun
	{
		legs pb_minigun_stand_run2idle duration 5 blendtime 100
	}
	// STAFF
	playerAnimType staff
	{
		// No animation
	}
	// GRENADES
	weaponclass grenade, prevdirection backward
	{
		legs pb_grenade_stand_run_b_2_idle duration 5 blendtime 100
	}
	weaponclass grenade, prevdirection left
	{
		legs pb_grenade_stand_run_l_2_idle duration 5 blendtime 100
	}
	weaponclass grenade, prevdirection right
	{
		legs pb_grenade_stand_run_r_2_idle duration 5 blendtime 100
	}
	weaponclass grenade
	{
		legs pb_grenade_stand_run2idle duration 5 blendtime 100
	}
	playerAnimType hold, prevdirection backward
	{
		legs pb_hold_stand_run_b_2_idle  grenadeAnim duration 5 blendtime 100
	}
	playerAnimType hold, prevdirection left
	{
		legs pb_hold_stand_run_l_2_idle  grenadeAnim duration 5 blendtime 100
	}
	playerAnimType hold, prevdirection right
	{
		legs pb_hold_stand_run_r_2_idle  grenadeAnim duration 5 blendtime 100
	}
	playerAnimType hold
	{
		legs pb_hold_stand_run2idle  grenadeAnim duration 5 blendtime 100
	}
	playerAnimType singleknife AND none, prevdirection backward
	{
		legs pb_knife_stand_run_b_2_idle duration 5 blendtime 100
	}
	playerAnimType singleknife AND none, prevdirection left
	{
		legs pb_knife_stand_run_l_2_idle duration 5 blendtime 100
	}
	playerAnimType singleknife AND none, prevdirection right
	{
		legs pb_knife_stand_run_r_2_idle duration 5 blendtime 100
	}
	playerAnimType singleknife AND none
	{
		legs pb_knife_stand_run2idle duration 5 blendtime 100
	}
	playerAnimType dualwield AND ballisticknife, prevdirection backward
	{
		legs pb_dw_stand_run_b_2_idle duration 5 blendtime 100
	}
	playerAnimType dualwield AND ballisticknife, prevdirection left
	{
		legs pb_dw_stand_run_l_2_idle duration 5 blendtime 100
	}
	playerAnimType dualwield AND ballisticknife, prevdirection right
	{
		legs pb_dw_stand_run_r_2_idle duration 5 blendtime 100
	}
	playerAnimType dualwield AND ballisticknife
	{
		legs pb_dw_stand_run2idle duration 5 blendtime 100
	}
	playerAnimType riotshield, prevdirection backward
	{
		legs pb_riot_stand_run_b_2_idle duration 5 blendtime 100
	}
	playerAnimType riotshield, prevdirection left
	{
		legs pb_riot_stand_run_l_2_idle duration 5 blendtime 100
	}
	playerAnimType riotshield, prevdirection right
	{
		legs pb_riot_stand_run_r_2_idle duration 5 blendtime 100
	}
	playerAnimType riotshield
	{
		legs pb_riot_stand_run2idle duration 5 blendtime 100
	}
	weaponclass rocketlauncher, prevdirection backward
	{
		legs pb_rpg_stand_run_b_2_idle duration 5 blendtime 100
	}
	weaponclass rocketlauncher, prevdirection left
	{
		legs pb_rpg_stand_run_l_2_idle duration 5 blendtime 100
	}
	weaponclass rocketlauncher, prevdirection right
	{
		legs pb_rpg_stand_run_r_2_idle duration 5 blendtime 100
	}
	weaponclass rocketlauncher
	{
		legs pb_rpg_stand_run2idle duration 5 blendtime 100
	}
	weaponclass pistol AND pistol_spread, prevdirection backward
	{
		legs pb_pistol_stand_run_b_2_idle duration 5 blendtime 100
	}
	weaponclass pistol AND pistol_spread, prevdirection left
	{
		legs pb_pistol_stand_run_l_2_idle duration 5 blendtime 100
	}
	weaponclass pistol AND pistol_spread, prevdirection right
	{
		legs pb_pistol_stand_run_r_2_idle duration 5 blendtime 100
	}
	weaponclass pistol AND pistol_spread
	{
		legs pb_pistol_stand_run2idle duration 5 blendtime 100
	}
	// DEFAULT
	prevdirection backward
	{
		legs pb_rifle_stand_run_b_2_idle duration 5 blendtime 100
	}
	prevdirection left
	{
		legs pb_rifle_stand_run_l_2_idle duration 5 blendtime 100
	}
	prevdirection right
	{
		legs pb_rifle_stand_run_r_2_idle duration 5 blendtime 100
	}
	default
	{
		legs pb_rifle_stand_run2idle duration 5 blendtime 100
	}
}

jump
{
	playerAnimType turned
	{
		legs pb_zombie_standjump_takeoff duration 5 blendtime 100
	}
	playerAnimType riotshield, movestatus run
	{
		legs pb_riotshield_runjump_takeoff duration 5 blendtime 100
	}
	playerAnimType riotshield
	{
		legs pb_riotshield_standjump_takeoff duration 5 blendtime 100
	}
	// HOLD
	playerAnimType hold, direction backward
	{
		legs pb_standjump_takeoff_satchel  grenadeAnim duration 5 blendtime 100
	}
	playerAnimType hold
	{
		legs pb_standjump_takeoff_satchel  grenadeAnim duration 5 blendtime 100
	}
	// DUAL WIELD
	playerAnimType dualwield AND ballisticknife, direction backward
	{
		legs pb_dw_standjump_takeoff duration 5 blendtime 100
	}
	playerAnimType dualwield AND ballisticknife
	{
		legs pb_dw_standjump_takeoff duration 5 blendtime 100
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none, movestatus moving
	{
		legs pb_knife_runjump_takeoff duration 5 blendtime 100
	}
	playerAnimType singleknife AND none, direction backward
	{
		legs pb_knife_standjump_takeoff duration 5 blendtime 100
	}
	playerAnimType singleknife AND none
	{
		legs pb_knife_standjump_takeoff duration 5 blendtime 100
	}
	// MINIGUN
	playerAnimType minigun, direction backward
	{
		legs pb_minigun_standjump_takeoff duration 5 blendtime 100
	}
	playerAnimType minigun, movestatus moving
	{
		legs pb_minigun_runjump_takeoff duration 5 blendtime 100
	}
	playerAnimType minigun
	{
		legs pb_minigun_standjump_takeoff duration 5 blendtime 100
	}
	// STAFF
	playerAnimType staff, direction backward
	{
		legs pb_staff_standjump_takeoff duration 5 blendtime 100
	}
	playerAnimType staff, movestatus run
	{
		legs pb_staff_runjump_takeoff duration 5 blendtime 100
	}
	playerAnimType staff
	{
		legs pb_staff_standjump_takeoff duration 5 blendtime 100
	}
	// RPG
	weaponclass rocketlauncher, direction backward
	{
		legs pb_rpg_standjump_takeoff duration 5 blendtime 100
	}
	weaponclass rocketlauncher, movestatus run
	{
		legs pb_rpg_runjump_takeoff duration 5 blendtime 100
	}
	weaponclass rocketlauncher
	{
		legs pb_rpg_standjump_takeoff duration 5 blendtime 100
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly, direction backward
	{
		legs pb_grenade_standjump_takeoff duration 5 blendtime 100 grenadeAnim
	}
	weaponclass grenade, playerAnimType grenadeonly, movestatus run
	{
		legs pb_grenade_runjump_takeoff duration 5 blendtime 100 grenadeAnim
	}
	weaponclass grenade, playerAnimType grenadeonly
	{
		legs pb_grenade_standjump_takeoff duration 5 blendtime 100 grenadeAnim
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, direction backward
	{
		legs pb_standjump_takeoff_pistol duration 5 blendtime 100
	}
	weaponclass pistol AND pistol_spread, movestatus run
	{
		legs pb_runjump_takeoff_pistol duration 5 blendtime 100
	}
	weaponclass pistol AND pistol_spread
	{
		legs pb_standjump_takeoff_pistol duration 5 blendtime 100
	}
	// RPG
	weaponclass rocketlauncher, direction backward
	{
		legs pb_standjump_takeoff duration 5 blendtime 100
	}
	weaponclass rocketlauncher, movestatus run
	{
		legs pb_runjump_takeoff duration 5 blendtime 100
	}
	weaponclass rocketlauncher
	{
		legs pb_standjump_takeoff duration 5 blendtime 100
	}
	// DEFAULT
	direction backward
	{
		legs pb_standjump_takeoff duration 5 blendtime 100
	}
	direction left
	{
		legs pb_rifle_stand_leftjump_takeoff duration 5 blendtime 100
	}
	direction right
	{
		legs pb_rifle_stand_rightjump_takeoff duration 5 blendtime 100
	}
	movestatus run
	{
		legs pb_runjump_takeoff duration 5 blendtime 100
	}
	default
	{
		legs pb_standjump_takeoff duration 5 blendtime 100
	}
}

land
{
	playerAnimType turned
	{
		legs pb_zombie_standjump_land duration 100 blendtime 5
	}
	playerAnimType riotshield, movestatus run
	{
		legs pb_riotshield_runjump_land duration 100 blendtime 5
	}
	playerAnimType riotshield
	{
		legs pb_riotshield_standjump_land duration 100 blendtime 5
	}
	// HOLD
	playerAnimType hold
	{
		legs pb_standjump_land_satchel grenadeAnim duration 100 blendtime 5
	}
	// DUAL WIELD
	playerAnimType dualwield AND ballisticknife
	{
		legs pb_dw_standjump_land duration 100 blendtime 50
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none, movestatus run
	{
		legs pb_knife_runjump_land duration 100 blendtime 50
	}
	playerAnimType singleknife AND none
	{
		legs pb_knife_standjump_land duration 100 blendtime 50
	}
	// MINIGUN
	playerAnimType minigun, movestatus run
	{
		legs pb_minigun_runjump_land duration 100 blendtime 50
	}
	playerAnimType minigun
	{
		legs pb_minigun_standjump_land duration 100 blendtime 50
	}
	// STAFF
	playerAnimType staff, movestatus run
	{
		legs pb_staff_runjump_land duration 100 blendtime 50
	}
	playerAnimType staff
	{
		legs pb_staff_standjump_land duration 100 blendtime 50
	}
	// RPG
	weaponclass rocketlauncher, movestatus run
	{
		legs pb_rpg_runjump_land duration 100 blendtime 50
	}
	weaponclass rocketlauncher
	{
		legs pb_rpg_standjump_land duration 100 blendtime 50
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly, movestatus run
	{
		legs pb_grenade_runjump_land duration 100 blendtime 5 grenadeAnim
	}
	weaponclass grenade, playerAnimType grenadeonly
	{
		legs pb_grenade_standjump_land duration 100 blendtime 50 grenadeAnim
	}
	// PISTOL
	weaponclass pistol AND pistol_spread, movestatus run
	{
		legs pb_runjump_land_pistol duration 100 blendtime 5
	}
	weaponclass pistol AND pistol_spread, playerAnimType grenadeonly
	{
		legs pb_standjump_land_pistol duration 100 blendtime 50
	}
	// DEFAULT
	direction left
	{
		legs pb_rifle_stand_leftjump_land duration 100 blendtime 50
	}
	direction right
	{
		legs pb_rifle_stand_rightjump_land duration 100 blendtime 50
	}
	movestatus run
	{
		legs pb_runjump_land duration 100 blendtime 5
	}
	default
	{
		legs pb_standjump_land duration 100 blendtime 50
	}
}

shellshock
{
	// LASTSTAND
	perk laststand
	{
		// No animation
	}
	// RADIO
	playerAnimType radio
	{
		// No animation
	}
	// TABLET
	playerAnimType tablet
	{
		// No animation
	}
	// MINIGUN
	playerAnimType minigun
	{
		// No animation
	}
	// STAFF
	playerAnimType staff, stance prone
	{
		torso pt_staff_prone_shellshock
	}
	playerAnimType staff, stance crouch
	{
		torso pt_staff_crouch_shellshock
	}
	playerAnimType staff
	{
		torso pt_staff_stand_shellshock
	}
	// RIOTSHIELD
	playerAnimType riotshield, stance crouch
	{
		torso pb_riotshield_crouch_shellshock
	}
	playerAnimType riotshield
	{
		torso pb_riotshield_shellshock
	}
	// HOLD
	playerAnimType hold, stance prone
	{
		torso pb_hold_prone_shellshock  grenadeAnim blendtime 50
	}
	playerAnimType hold, stance crouch
	{
		torso pb_crouch_shellshock_hold grenadeAnim blendtime 50
	}
	playerAnimType hold
	{
		torso pb_stand_shellshock_hold grenadeAnim blendtime 50
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife, stance prone
	{
		torso pb_dw_prone_shellshock blendtime 50
	}
	playerAnimType dualwield AND ballisticknife, stance crouch
	{
		torso pb_dw_crouch_shellshock blendtime 50
	}
	playerAnimType dualwield AND ballisticknife
	{
		torso pb_dw_stand_shellshock blendtime 50
	}
	// ZIPLINE
	playerAnimType zipline
	{
		// No animation
	}
	// DEFAULT
	stance prone
	{
		torso pb_rifle_prone_shellshock blendtime 50
	}
	stance crouch
	{
		torso pb_crouch_shellshock blendtime 50
	}
	default
	{
		torso pb_stand_shellshock blendtime 50
	}
}

// FLINCHING
flinch
{
	// LASTSTAND
		perk laststand
		{
			// No flinch, since this causes issues in the transition
		}
	// TURNED
		playerAnimType turned
		{
			// No animation
		}
	// MINIGUN
		playerAnimType minigun
		{
			// No animation
		}
	// RIOTSHIELD
		playerAnimType riotshield
		{
			// No animation
		}
		riotshieldnext
		{
			// No animation
		}
		nextplayeranimtype riotshield
		{
			// No animation
		}
	// RADIO
		playerAnimType radio
		{
			// No animation
		}
	// TABLET
		playerAnimType tablet
		{
			// No animation
		}
	// BRIEFCASE
		playerAnimType briefcase
		{
			// No animation
		}
	// SINGLE KNIFE
		// Prone
		playerAnimType singleknife, dmgdirection right, stance prone
		{
			torso pt_knife_prone_flinch_right
		}
		playerAnimType singleknife, dmgdirection left, stance prone
		{
			torso pt_knife_prone_flinch_left
		}
		playerAnimType singleknife, dmgdirection back, stance prone
		{
			torso pt_knife_prone_flinch_back
		}
		playerAnimType singleknife, dmgdirection front, stance prone
		{
			torso pt_knife_prone_flinch_forward
		}
		// Crouch
		playerAnimType singleknife, dmgdirection right, stance crouch
		{
			torso pt_knife_crouch_flinch_right
		}
		playerAnimType singleknife, dmgdirection left, stance crouch
		{
			torso pt_knife_crouch_flinch_left
		}
		playerAnimType singleknife, dmgdirection back, stance crouch
		{
			torso pt_knife_crouch_flinch_back
		}
		playerAnimType singleknife, dmgdirection front, stance crouch
		{
			torso pt_knife_crouch_flinch_forward
		}
		// Stand
		playerAnimType singleknife, dmgdirection right
		{
			torso pt_knife_stand_flinch_right
		}
		playerAnimType singleknife, dmgdirection left
		{
			torso pt_knife_stand_flinch_left
		}
		playerAnimType singleknife, dmgdirection back
		{
			torso pt_knife_stand_flinch_back
		}
		playerAnimType singleknife, dmgdirection front
		{
			torso pt_knife_stand_flinch_forward
		}
	// HOLD
		// Prone
		playerAnimType hold, dmgdirection right, stance prone
		{
			torso pt_hold_prone_flinch_right grenadeAnim
		}
		playerAnimType hold, dmgdirection left, stance prone
		{
			torso pt_hold_prone_flinch_left grenadeAnim
		}
		playerAnimType hold, dmgdirection back, stance prone
		{
			torso pt_hold_prone_flinch_back grenadeAnim
		}
		playerAnimType hold, dmgdirection front, stance prone
		{
			torso pt_hold_prone_flinch_forward grenadeAnim
		}
		// Crouch
		playerAnimType hold, dmgdirection right, stance crouch
		{
			torso pt_hold_crouch_flinch_right grenadeAnim
		}
		playerAnimType hold, dmgdirection left, stance crouch
		{
			torso pt_hold_crouch_flinch_left grenadeAnim
		}
		playerAnimType hold, dmgdirection back, stance crouch
		{
			torso pt_hold_crouch_flinch_back grenadeAnim
		}
		playerAnimType hold, dmgdirection front, stance crouch
		{
			torso pt_hold_crouch_flinch_back grenadeAnim
		}
		// Stand
		playerAnimType hold, dmgdirection right
		{
			torso pt_hold_stand_flinch_right grenadeAnim
		}
		playerAnimType hold, dmgdirection left
		{
			torso pt_hold_stand_flinch_left grenadeAnim
		}
		playerAnimType hold, dmgdirection back
		{
			torso pt_hold_stand_flinch_back grenadeAnim
		}
		playerAnimType hold, dmgdirection front
		{
			torso pt_hold_stand_flinch_forward grenadeAnim
		}
	// DUAL WIELD
		// Prone
		playerAnimType dualwield AND ballisticknife, dmgdirection right, stance prone
		{
			torso pt_dw_prone_flinch_right
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection left, stance prone
		{
			torso pt_dw_prone_flinch_left
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection back, stance prone
		{
			torso pt_dw_prone_flinch_back
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection front, stance prone
		{
			torso pt_dw_prone_flinch_forward
		}
		// Crouch
		playerAnimType dualwield AND ballisticknife, dmgdirection right, stance crouch
		{
			torso pt_dw_crouch_flinch_right
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection left, stance crouch
		{
			torso pt_dw_crouch_flinch_left
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection back, stance crouch
		{
			torso pt_dw_crouch_flinch_back
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection front, stance crouch
		{
			torso pt_dw_crouch_flinch_back
		}
		// Stand
		playerAnimType dualwield AND ballisticknife, dmgdirection right
		{
			torso pt_dw_stand_flinch_right
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection left
		{
			torso pt_dw_stand_flinch_left
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection back
		{
			torso pt_dw_stand_flinch_back
		}
		playerAnimType dualwield AND ballisticknife, dmgdirection front
		{
			torso pt_dw_stand_flinch_forward
		}
	// REMOTE CONTROL
		// Prone
//		playerAnimType remotecontrol, dmgdirection left, stance prone
//		{
//			torso pt_rc_prone_flinch_left
//		}
//		playerAnimType remotecontrol, dmgdirection right, stance prone
//		{
//			torso pt_rc_prone_flinch_right
//		}
//		playerAnimType remotecontrol, dmgdirection front, stance prone
//		{
//			torso pt_rc_prone_flinch_forward
//		}
//		playerAnimType remotecontrol, dmgdirection back, stance prone
//		{
//			torso pt_rc_prone_flinch_back
//		}
//		// Crouch
//		playerAnimType remotecontrol, dmgdirection front, stance crouch
//		{
//			torso pt_rc_crouch_flinch_forward
//		}
//		playerAnimType remotecontrol, dmgdirection back, stance crouch
//		{
//			torso pt_rc_crouch_flinch_back
//		}
//		playerAnimType remotecontrol, dmgdirection left, stance crouch
//		{
//			torso pt_rc_crouch_flinch_left
//		}
//		playerAnimType remotecontrol, dmgdirection right, stance crouch
//		{
//			torso pt_rc_crouch_flinch_right
//		}
//		// Stand
//		playerAnimType remotecontrol, dmgdirection front
//		{
//			torso pt_rc_stand_flinch_forward
//		}
//		playerAnimType remotecontrol, dmgdirection back
//		{
//			torso pt_rc_stand_flinch_back
//		}
//		playerAnimType remotecontrol, dmgdirection left
//		{
//			torso pt_rc_stand_flinch_left
//		}
//		playerAnimType remotecontrol, dmgdirection right
//		{
//			torso pt_rc_stand_flinch_right
//		}
	// ZIPLINE
		playerAnimType zipline
		{
			// No animation
		}
	// STAFF
		// Prone
		playerAnimType staff, dmgdirection right, stance prone
		{
			torso pt_staff_prone_flinch_right
		}
		playerAnimType staff, dmgdirection left, stance prone
		{
			torso pt_staff_prone_flinch_left
		}
		playerAnimType staff, dmgdirection back, stance prone
		{
			torso pt_staff_prone_flinch_back
		}
		playerAnimType staff, dmgdirection front, stance prone
		{
			torso pt_staff_prone_flinch_forward
		}
		// Crouch
		playerAnimType staff, dmgdirection right, stance crouch
		{
			torso pt_staff_crouch_flinch_right
		}
		playerAnimType staff, dmgdirection left, stance crouch
		{
			torso pt_staff_crouch_flinch_left
		}
		playerAnimType staff, dmgdirection back, stance crouch
		{
			torso pt_staff_crouch_flinch_back
		}
		playerAnimType staff, dmgdirection front, stance crouch
		{
			torso pt_staff_crouch_flinch_forward
		}
		// Stand
		playerAnimType staff, dmgdirection right
		{
			torso pt_staff_stand_flinch_right
		}
		playerAnimType staff, dmgdirection left
		{
			torso pt_staff_stand_flinch_left
		}
		playerAnimType staff, dmgdirection back
		{
			torso pt_staff_stand_flinch_back
		}
		playerAnimType staff, dmgdirection front
		{
			torso pt_staff_stand_flinch_forward
		}
	// GRENADE
		// Prone
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection right, stance prone
		{
			torso pt_prone_flinch_grenade_right grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection left, stance prone
		{
			torso pt_prone_flinch_grenade_left grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection back, stance prone
		{
			torso pt_prone_flinch_grenade_back grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection front, stance prone
		{
			torso pt_prone_flinch_grenade_forward grenadeAnim
		}
		// Crouch
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection right, stance crouch
		{
			torso pt_crouch_flinch_grenade_right grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection left, stance crouch
		{
			torso pt_crouch_flinch_grenade_left grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection back, stance crouch
		{
			torso pt_crouch_flinch_grenade_back grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection front, stance crouch
		{
			torso pt_crouch_flinch_grenade_back grenadeAnim
		}
		// Stand
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection right
		{
			torso pt_stand_flinch_grenade_right grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection left
		{
			torso pt_stand_flinch_grenade_left grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection back
		{
			torso pt_stand_flinch_grenade_back grenadeAnim
		}
		weaponclass grenade, playerAnimType grenadeonly, dmgdirection front
		{
			torso pt_stand_flinch_grenade_forward grenadeAnim
		}
	// PISTOL
		// Prone
		weaponclass pistol AND pistol_spread, dmgdirection right, stance prone
		{
			torso pt_prone_flinch_pistol_right
		}
		weaponclass pistol AND pistol_spread, dmgdirection left, stance prone
		{
			torso pt_prone_flinch_pistol_left
		}
		weaponclass pistol AND pistol_spread, dmgdirection back, stance prone
		{
			torso pt_prone_flinch_pistol_back
		}
		weaponclass pistol AND pistol_spread, dmgdirection front, stance prone
		{
			torso pt_prone_flinch_pistol_forward
		}
		// Crouch
		weaponclass pistol AND pistol_spread, dmgdirection right, stance crouch
		{
			torso pt_crouch_flinch_pistol_right
		}
		weaponclass pistol AND pistol_spread, dmgdirection left, stance crouch
		{
			torso pt_crouch_flinch_pistol_left
		}
		weaponclass pistol AND pistol_spread, dmgdirection back, stance crouch
		{
			torso pt_crouch_flinch_pistol_back
		}
		weaponclass pistol AND pistol_spread, dmgdirection front, stance crouch
		{
			torso pt_crouch_flinch_pistol_back
		}
		// Stand
		weaponclass pistol AND pistol_spread, dmgdirection right
		{
			torso pt_stand_flinch_pistol_right
		}
		weaponclass pistol AND pistol_spread, dmgdirection left
		{
			torso pt_stand_flinch_pistol_left
		}
		weaponclass pistol AND pistol_spread, dmgdirection back
		{
			torso pt_stand_flinch_pistol_back
		}
		weaponclass pistol AND pistol_spread, dmgdirection front
		{
			torso pt_stand_flinch_pistol_forward
		}
	// DEFAULT
		// Prone
		dmgdirection right, stance prone
		{
			torso pt_prone_flinch_right
		}
		dmgdirection left, stance prone
		{
			torso pt_prone_flinch_left
		}
		dmgdirection back, stance prone
		{
			torso pt_prone_flinch_back
		}
		dmgdirection front, stance prone
		{
			torso pt_prone_flinch_back
		}
		// Crouch
		dmgdirection right, stance crouch
		{
			torso pt_crouch_flinch_right
		}
		dmgdirection left, stance crouch
		{
			torso pt_crouch_flinch_left
		}
		dmgdirection back, stance crouch
		{
			torso pt_crouch_flinch_back
		}
		dmgdirection front, stance crouch
		{
			torso pt_crouch_flinch_back
		}
		// Stand
		dmgdirection right
		{
			torso pt_stand_flinch_right
		}
		dmgdirection left
		{
			torso pt_stand_flinch_left
		}
		dmgdirection back
		{
			torso pt_stand_flinch_back
		}
		dmgdirection front
		{
			torso pt_stand_flinch_forward
		}
}

DEATH
{
	// TURNED
	playerAnimType turned
	{
		both pb_zombie_death_v1
		both pb_zombie_death_v2
	}
	// LASTSTAND
	perk laststand, dmgType suicide
	{
		both pb_laststand_suicide_death
	}
	default
	{
		// No animation, we should never die in zombies
	}
	//perk laststand
	//{
	//	both pb_laststand_death
	//}
	//stance prone
	//{
	//	both pb_prone_death_quickdeath
	//}
	//// GAS
	//dmgType gas, stance crouch
	//{
	//	both pb_crouch_death_fetal
	//	both pb_crouch_death_falltohands
	//}
	//dmgType gas
	//{
	//	both pb_stand_death_head_collapse
	//	both pb_stand_death_neckdeath_thrash
	//}
	// EXPLOSIVE
	//dmgType explosive, dmgDirection front
	//{
	//	both pb_death_flyback
	//	both pb_death_flatonback
	//	both pb_death_flyback_far
	//	both pb_death_armslegsforward
	//	both pb_death_armslegsforward_b
	//	both pb_death_upontoback
	//}
	//dmgType explosive, dmgDirection back
	//{
	//	both pb_death_forwardtoface
	//	both pb_death_faceplant
	//}
	//dmgType explosive, dmgDirection left
	//{
	//	both pb_death_legsout_right
	//	both pb_death_jackiespin_right
	//}
	//dmgType explosive, dmgDirection right
	//{
	//	both pb_death_legsout_left
	//	both pb_death_jackiespin_left
	//}
	//dmgType explosive
	//{
	//	both pb_death_jackiespin_inplace
	//	both pb_death_jackiespin_vertical
	//}
	// SHOTGUN
	//dmgType normal_shotgun, dmgDirection front, stance crouch
	//{
	//	both pb_crouch_death_shotgun_front
	//}
	//dmgType normal_shotgun, dmgDirection back, stance crouch
	//{
	//	both pb_crouch_death_shotgun_back
	//}
	//dmgType normal_shotgun, dmgDirection left, stance crouch
	//{
	//	both pb_crouch_death_shotgun_left
	//}
	//dmgType normal_shotgun, dmgDirection right, stance crouch
	//{
	//	both pb_crouch_death_shotgun_right
	//}
	//dmgType normal_shotgun, dmgDirection front
	//{
	//	both pb_death_shotgun_front
	//}
	//dmgType normal_shotgun, dmgDirection back
	//{
	//	both pb_death_shotgun_back
	//}
	//dmgType normal_shotgun, dmgDirection left
	//{
	//	both pb_death_shotgun_left
	//}
	//dmgType normal_shotgun, dmgDirection right
	//{
	//	both pb_death_shotgun_right
	//}
	// HEADSHOT
	//dmgType headshot, dmgDirection front, stance crouch
	//{
	//	both pb_crouch_death_headshot_front
	//}
	//dmgType headshot, dmgDirection back, stance crouch
	//{
	//	both pb_crouch_death_headshot_back
	//}
	//dmgType headshot, dmgDirection left, stance crouch
	//{
	//	both pb_crouch_death_headshot_left
	//}
	//dmgType headshot, dmgDirection right, stance crouch
	//{
	//	both pb_crouch_death_headshot_right
	//}
	//dmgType headshot, dmgDirection front
	//{
	//	both pb_death_headshot_front
	//	both pb_death_headshot_front_v2
	//}
	//dmgType headshot, dmgDirection back
	//{
	//	both pb_death_headshot_back
	//}
	//dmgType headshot, dmgDirection left
	//{
	//	both pb_death_headshot_left
	//}
	//dmgType headshot, dmgDirection right
	//{
	//	both pb_death_headshot_right
	//}
	// MELEE BASH
	//dmgType meleebash, dmgDirection front, stance crouch
	//{
	//	both pb_crouch_death_shieldbash_front
	//}
	//dmgType meleebash, dmgDirection back, stance crouch
	//{
	//	both pb_crouch_death_shieldbash_back
	//}
	//dmgType meleebash, dmgDirection left, stance crouch
	//{
	//	both pb_crouch_death_shieldbash_left
	//}
	//dmgType meleebash, dmgDirection right, stance crouch
	//{
	//	both pb_crouch_death_shieldbash_right
	//}
	//dmgType meleebash, dmgDirection front
	//{
	//	both pb_death_shieldbash_front
	//}
	//dmgType meleebash, dmgDirection back
	//{
	//	both pb_death_shieldbash_back
	//}
	//dmgType meleebash, dmgDirection left
	//{
	//	both pb_death_shieldbash_left
	//}
	//dmgType meleebash, dmgDirection right
	//{
	//	both pb_death_shieldbash_right
	//}
	// MELEE
	//dmgType melee, dmgDirection front, stance crouch
	//{
	//	both pb_crouch_death_melee_front
	//}
	//dmgType melee, dmgDirection back, stance crouch
	//{
	//	both pb_crouch_death_melee_back
	//}
	//dmgType melee, dmgDirection left, stance crouch
	//{
	//	both pb_crouch_death_melee_left
	//}
	//dmgType melee, dmgDirection right, stance crouch
	//{
	//	both pb_crouch_death_melee_right
	//}
	//dmgType melee, dmgDirection front
	//{
	//	both pb_death_melee_front
	//}
	//dmgType melee, dmgDirection back
	//{
	//	both pb_death_melee_back
	//	both pb_death_melee_back_v2
	//}
	//dmgType melee, dmgDirection left
	//{
	//	both pb_death_melee_left
	//}
	//dmgType melee, dmgDirection right
	//{
	//	both pb_death_melee_right
	//}
	// DEFAULT
	//movestatus run, stance crouch
	//{
	//	both pb_crouchrun_death_drop
	//	both pb_crouchrun_death_crumple
	//}
	//stance crouch
	//{
	//	both pb_crouch_death_headshot_front
	//	both pb_crouch_death_clutchchest
	//	both pb_crouch_death_flip
	//	both pb_crouch_death_fetal
	//	both pb_crouch_death_falltohands
	//}
	//movestatus run, direction backward
	//{
	//	both pb_death_run_back
	//}
	//movestatus run, direction left
	//{
	//	both pb_death_run_left
	//}
	//movestatus run, direction right
	//{
	//	both pb_death_run_right
	//}
	//movestatus run
	//{
	//	both pb_death_run_forward_crumple
	//	both pb_death_run_onfront
	//	both pb_death_run_stumble
	//}
	//default
	//{
	//	both pb_stand_death_neckdeath
	//	both pb_stand_death_headchest_topple
	//	both pb_stand_death_frontspin
	//	both pb_stand_death_nervedeath
	//	both pb_stand_death_legs
	//	both pb_stand_death_lowerback
	//	both pb_stand_death_head_collapse
	//	both pb_stand_death_neckdeath_thrash
	//}
}

dtp_takeoff
{
	// HOLD
	playerAnimType hold
	{
		both pb_hold_dive_prone  grenadeAnim animrate 1
	}
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife
	{
		both pb_dw_dive_prone animrate 1
	}
	// SINGE KNIFE
	playerAnimType singleknife AND none
	{
		both pb_knife_dive_prone animrate 1
	}
	// STAFF
	playerAnimType staff
	{
		both pb_staff_dive2prone animrate 1
	}
	// PISTOL
	weaponclass pistol AND pistol_spread
	{
		both pb_dive_prone_pistol animrate 1
	}
	// RPG
	weaponclass rocketlauncher
	{
		both pb_rpg_dive_prone animrate 1
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_dive_prone animrate 1
	}
	// DEFAULT
	default
	{
		both pb_dive_prone animrate 1
	}
}

dtp_land
{
	// DUALWIELD
	playerAnimType dualwield AND ballisticknife
	{
		both pb_dw_dive_prone_land animrate 1
	}
	// SINGLE KNIFE
	playerAnimType singleknife AND none
	{
		both pb_knife_dive_prone_land animrate 1
	}
	// HOLD
	playerAnimType hold
	{
		both pb_hold_dive_prone_land  grenadeAnim animrate 1
	}
	// STAFF
	playerAnimType staff
	{
		both pb_staff_dive2prone_land
	}
	// PISTOL
	weaponclass pistol AND pistol_spread
	{
		both pb_pistol_dive_prone_land animrate 1
	}
	// RPG
	weaponclass rocketlauncher
	{
		both pb_rpg_dive_prone_land animrate 1
	}
	// GRENADE
	weaponclass grenade, playerAnimType grenadeonly
	{
		both pb_grenade_dive_prone_land animrate 1
	}
	// DEFAULT
	default
	{
		both pb_dive_prone_land animrate 1 blendtime 133
	}
}

laststand_suicide
{
	default
	{
		both pb_laststand_suicide
	}
}

flared
{
	default
	{
		// No animation
	}
}

prime_grenade
{
	playerAnimType reviver
	{
		// No animation
	}
	playerAnimType hold
	{
		// No animation, since these don't have a pin
	}
	playerAnimType hatchet
	{
		// No animation, since these don't have a pin
	}
	stance prone
	{
		torso pt_grenade_prone_prime grenadeAnim
	}
	stance crouch
	{
		torso pt_grenade_crouch_prime grenadeAnim
	}
	default
	{
		torso pt_grenade_stand_prime
	}
}

//scriptevent
//{
//	// DEFAULT
//	event breach_shoulder
//	{
//		both pb_breach_shoulder
//	}
//	event breach_slide
//	{
//		both pb_breach_slide
//	}
//	event breach_lift
//	{
//		both pb_breach_lift
//	}
//}

forceload
{
	head
	pf_casual_idle
	pf_alert_idle
	pf_firing
	pf_melee
	pf_pain
	pf_death

	f_attack_zombie_v1
	f_attack_zombie_v2
	f_attack_zombie_v3
	f_attack_zombie_v4
	f_attack_zombie_v5

	f_death_zombie_v1
	f_death_zombie_v2
	f_death_zombie_v3
	f_death_zombie_v4
	f_death_zombie_v5

	f_idle_zombie_v1
	f_idle_zombie_v2
	f_idle_zombie_v3
	f_idle_zombie_v4
	f_idle_zombie_v5

	f_locomotion_zombie_v1
	f_locomotion_zombie_v2
	f_locomotion_zombie_v3
	f_locomotion_zombie_v4
	f_locomotion_zombie_v5


//	pb_huey_minigun_aim
//	pb_huey_minigun_aim_down
//	pb_huey_minigun_aim_up
//	pb_huey_gunner_aim_60left_level
//	pb_huey_gunner_aim_60right_level
//	pb_huey_gunner_aim_60down_60left
//	pb_huey_gunner_aim_60down_60right
//	pb_huey_gunner_aim_60up_60left
//	pb_huey_gunner_aim_60up_60right
	fake_gunner_aim
}